import { test, expect, type Page } from '@playwright/test';
const password = process.env.TEST_BROWSER_PASSWORD;
if (!password) throw new Error('Falta la contraseña del entorno de navegador aislado.');

test.beforeEach(async ({ page }) => {
  const response = await page.goto('/login');
  expect(response?.ok()).toBe(true);
  const html = await response!.text();
  const data = await page.evaluate(html => {
    const document = new DOMParser().parseFromString(html, 'text/html');
    return JSON.parse(document.querySelector('script[data-page="app"]')!.textContent!);
  }, html);
  expect(data.props.test_environment, 'La instancia debe identificarse como testing antes de enviar credenciales o escribir').toBe(true);
});

async function login(page: Page, email = 'admin@erronk2d.test') {
  await page.goto('/login');
  await page.getByLabel('Correo electrónico').fill(email);
  await page.getByLabel('Contraseña', { exact: true }).fill(password!);
  await page.getByRole('button', { name: 'Entrar a Erronk2D' }).click();
  await expect(page.getByRole('heading', { name: 'Los retos, en perspectiva.' })).toBeVisible();
}

test('navegación: lateral plegable, páginas propias, recarga e historial', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  const sidebar = page.getByRole('complementary', { name: 'Menú lateral' });
  await page.getByRole('button', { name: 'Contraer menú lateral', exact: true }).click();
  await expect(sidebar).toHaveCSS('width', '80px');
  await page.getByRole('button', { name: 'Organización', exact: true }).click();
  await page.getByRole('link', { name: 'Profesor', exact: true }).click();
  await expect(page).toHaveURL(/\/setup\/teachers$/);
  await expect(page.getByRole('heading', { name: 'Profesor.', level: 1, exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Profesor', exact: true })).toHaveAttribute('aria-current', 'page');
  await page.reload();
  await expect(sidebar).toHaveCSS('width', '80px');
  await page.screenshot({ path: 'test-results/sidebar-collapsed.png', fullPage: true });
  await page.getByRole('link', { name: 'Módulos', exact: true }).click();
  await expect(page).toHaveURL(/\/setup\/modules$/);
  await page.goBack();
  await expect(page).toHaveURL(/\/setup\/teachers$/);
  await expect(page.getByRole('heading', { name: 'Profesor.', level: 1, exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Expandir menú lateral', exact: true }).click();
  await expect(sidebar).toHaveCSS('width', '252px');
  await page.getByRole('link', { name: 'Grupos', exact: true }).click();
  await expect(page).toHaveURL(/\/setup\/classrooms$/);
  await expect(page.getByRole('heading', { name: 'Grupos y matrículas', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Cursos académicos', exact: true })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/sidebar-expanded.png', fullPage: true });
  await page.getByRole('link', { name: 'Grupos', exact: true }).focus();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Organización', exact: true })).toHaveAttribute('aria-expanded', 'false');
  await expect(page.getByRole('button', { name: 'Organización', exact: true })).toBeFocused();
  await page.goto('/setup/students');
  await expect(page.getByRole('heading', { name: 'Estudiante.', level: 1, exact: true })).toBeVisible();
  await expect(sidebar).toHaveCSS('width', '252px');
  expect(errors).toEqual([]);
});

test('navegación móvil: submenú accesible y sin desbordamiento', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 390, height: 844 });
  await login(page);
  const selectorBottom = await page.locator('.academic-selector').evaluate(el => el.getBoundingClientRect().bottom);
  const contentTop = await page.locator('.topline').evaluate(el => el.getBoundingClientRect().top);
  expect(contentTop).toBeGreaterThan(selectorBottom);
  await page.getByRole('button', { name: 'Organización', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Estudiante', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/sidebar-mobile.png', fullPage: true });
  await page.getByRole('link', { name: 'Estudiante', exact: true }).click();
  await expect(page).toHaveURL(/\/setup\/students$/);
  await expect(page.getByRole('button', { name: 'Organización', exact: true })).toHaveAttribute('aria-expanded', 'false');
  await expect(page.getByRole('heading', { name: 'Estudiante.', level: 1, exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Organización', exact: true }).click();
  await page.getByRole('link', { name: 'Biblioteca de rúbricas', exact: true }).click();
  await expect(page).toHaveURL(/\/setup\/rubrics$/);
  await expect(page.getByRole('heading', { name: 'Biblioteca de rúbricas.', level: 1, exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('creación de reto: rúbricas compatibles y validación sin perder el formulario', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await page.getByRole('button', { name: 'Nuevo reto', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Nombre del reto').fill('Regresión de creación');
  await dialog.getByLabel('Descripción', { exact: true }).fill('Conservar este texto al validar.');
  await dialog.getByRole('combobox', { name: 'Evaluación', exact: true }).selectOption({ label: '1.ª Evaluación' });
  const modules = dialog.locator('fieldset').getByRole('checkbox');
  const teamRubric = dialog.getByRole('combobox', { name: 'Rúbrica del reto', exact: true });
  const teamOption = teamRubric.getByRole('option', { name: /Proyecto web/ });
  await expect(teamOption).toHaveJSProperty('disabled', true);
  for (const module of await modules.all()) await module.check();
  await expect(teamOption).toHaveJSProperty('disabled', false);
  await teamRubric.selectOption({ label: 'Proyecto web · Rúbrica de equipo' });
  await modules.last().uncheck();
  await expect(teamRubric).toHaveValue('');
  await expect(teamOption).toHaveJSProperty('disabled', true);
  await modules.last().check();
  await teamRubric.selectOption({ label: 'Proyecto web · Rúbrica de equipo' });
  await dialog.getByRole('combobox', { name: 'Rúbrica transversal', exact: true }).selectOption({ label: 'Aprender en equipo · Transversales' });

  await page.route('**/challenges', async route => {
    const data = route.request().postDataJSON();
    await route.continue({ postData: JSON.stringify({ ...data, module_ids: data.module_ids.slice(0, -1) }) });
  });
  await dialog.getByRole('button', { name: 'Crear reto', exact: true }).click();
  await expect(dialog.getByText('La rúbrica incluye criterios de módulos que no participan.', { exact: false })).toBeVisible();
  await expect(dialog.getByLabel('Nombre del reto')).toHaveValue('Regresión de creación');
  await expect(dialog.getByLabel('Descripción', { exact: true })).toHaveValue('Conservar este texto al validar.');
  await page.unroute('**/challenges');
  await dialog.getByRole('button', { name: 'Crear reto', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Regresión de creación', exact: true })).toBeVisible();
  await expect(dialog).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('profesorado: matriz, teclado, configuración y seguimiento', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await login(page);
  await page.screenshot({ path: 'test-results/dashboard.png', fullPage: true });
  await page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Una web para nuestra comunidad' }) }).click();
  await expect(page.locator('.matrix tbody tr')).toHaveCount(20);
  await expect(page.getByLabel('Progreso por tipo de evaluación')).toContainText('Exámenes');
  const first = page.getByLabel('Examen PROG de Ainhoa Agirre', { exact: true });
  const second = page.getByLabel('Examen DWEC de Ainhoa Agirre', { exact: true });
  const oldFirst = await first.inputValue(), oldSecond = await second.inputValue();
  await page.route(page.url(), async route => {
    if (route.request().method() === 'POST') await new Promise(resolve => setTimeout(resolve, 350));
    await route.continue();
  });
  try {
    await first.fill('7,1234');
    await first.press('Tab');
    await second.fill('8,4321');
    await second.press('Enter');
    await expect(page.getByText('Cambios guardados', { exact: true })).toBeVisible();
    await page.reload();
    await expect(first).toHaveValue('7.1234');
    await expect(second).toHaveValue('8.4321');
    await page.getByRole('button', { name: 'Transversales del profesorado', exact: true }).click();
    await expect(page.getByRole('combobox', { name: 'Estudiante a evaluar' }).locator('option')).toHaveCount(20);
    await expect(page.locator('.rubric-assessment tbody tr')).toHaveCount(4);
    await page.getByRole('button', { name: 'Volver a la matriz de notas' }).click();
    await page.getByRole('button', { name: 'Configurar reto', exact: true }).click();
    await expect(page.getByRole('dialog').getByText('Defensas por módulo')).toBeVisible();
    await page.keyboard.press('Escape');
    await page.screenshot({ path: 'test-results/matrix.png', fullPage: true });
  } finally {
    await first.fill(oldFirst); await first.press('Tab');
    await second.fill(oldSecond); await second.press('Enter');
    await expect(page.getByText('Cambios guardados', { exact: true })).toBeVisible();
  }
  await page.goto('/reports');
  await expect(page.getByRole('heading', { name: 'Cada Evaluación cuenta.' })).toBeVisible();
  await expect(page.locator('tbody tr')).toHaveCount(80);
  await page.goto('/setup');
  await page.getByRole('link', { name: 'Biblioteca de rúbricas', exact: true }).click();
  await page.getByRole('button', { name: 'Duplicar rúbrica' }).first().click();
  await expect(page.getByRole('heading', { name: /\(copia\)/ }).first()).toBeVisible();
  expect(errors).toEqual([]);
});

test('alumnado: autoevaluación, compañeros, resultado propio y móvil', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await login(page, 'alumno1@erronk2d.test');
  await page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Una web para nuestra comunidad' }) }).click();
  await expect(page.getByRole('button', { name: 'Mi autoevaluación', exact: true })).toBeVisible();
  await expect(page.locator('.person-tabs button')).toHaveCount(4);
  await expect(page.getByRole('heading', { name: 'Tus resultados publicados' })).toHaveCount(0);
  const chosen = page.locator('.student-rubric').first().locator('button.chosen');
  await chosen.click();
  await expect(page.getByRole('status')).toHaveText('Evaluación guardada');
  await page.goto('/');
  await page.locator('.challenge-card').filter({ has: page.locator('.badge.published') }).click();
  await expect(page.getByRole('heading', { name: 'Tus resultados publicados' })).toBeVisible();
  await expect(page.locator('.module-breakdowns section')).toHaveCount(4);
  await page.screenshot({ path: 'test-results/student-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});


test('organización: guardar una edición y cambiar de formulario sin arrastrar datos', async ({ page }) => {
  await login(page);
  await page.goto('/setup');
  await page.getByRole('link', { name: 'Estudiante', exact: true }).click();
  await page.getByRole('button', { name:'Editar Ainhoa Agirre', exact:true }).click();
  await page.getByRole('dialog').getByRole('button', { name:'Guardar', exact:true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('link', { name: 'Profesor', exact: true }).click();
  await page.getByRole('button', { name:'Profesor', exact:true }).last().click();
  await expect(page.getByRole('dialog', { name:'Crear Profesor', exact:true })).toBeVisible();
  await expect(page.getByRole('dialog').getByLabel('Nombre', { exact:true })).toHaveValue('');
  await expect(page.getByRole('dialog').getByLabel('Correo', { exact:true })).toHaveValue('');
  await page.keyboard.press('Escape');
});


test('organización: alta con diez caracteres y grupo, pestañas y renombrado del curso', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await page.goto('/setup');
  await page.getByRole('button', { name: 'Editar curso', exact: true }).first().click();
  const course = page.getByRole('dialog');
  await expect(course.getByLabel('Número de evaluaciones')).toHaveCount(0);
  await course.getByLabel('Nombre', { exact: true }).fill('Curso revisado en navegador');
  await course.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(course).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Curso revisado en navegador' })).toBeVisible();
  await page.getByRole('link', { name: 'Estudiante', exact: true }).click();
  await expect(page.getByRole('columnheader', { name: 'GRUPO', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Estudiante', exact: true }).last().click();
  const student = page.getByRole('dialog');
  await student.getByLabel('Nombre', { exact: true }).fill('Estudiante del navegador');
  await student.getByLabel('Correo', { exact: true }).fill('browser-student@example.test');
  await student.getByLabel('Contraseña inicial', { exact: false }).fill('Clave12345');
  await expect(student.getByLabel('Añadir matrícula en un grupo', { exact: false })).toHaveValue('');
  await student.getByLabel('Añadir matrícula en un grupo', { exact: false }).selectOption({ label: '2DAW-A' });
  await student.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(student).toHaveCount(0);
  await expect(page.getByRole('row').filter({ hasText: 'browser-student@example.test' })).toContainText('2DAW-A');
  await page.getByRole('link', { name: 'Profesor', exact: true }).click();
  await expect(page.getByText('browser-student@example.test')).toHaveCount(0);
  expect(errors).toEqual([]);
});


test('equipos: recuperar participantes y guardar dos equipos desde los selectores', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Reto vacío para pruebas' }) }).click();
  await page.getByRole('button', { name: 'Gestionar', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByText('Este reto no tiene estudiantes.', { exact: false })).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Guardar equipos', exact: true })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Incorporar estudiantes del grupo', exact: true }).click();
  const teams = dialog.locator('.team-editor > section');
  await expect(teams.first().getByRole('checkbox').first()).toBeVisible();
  await teams.first().getByRole('checkbox').nth(0).check();
  await teams.first().getByRole('checkbox').nth(1).check();
  await dialog.getByRole('button', { name: 'Añadir equipo', exact: true }).click();
  await expect(teams.nth(1).getByRole('checkbox').nth(0)).toBeDisabled();
  await teams.nth(1).getByRole('checkbox').nth(2).check();
  await teams.nth(1).getByRole('checkbox').nth(3).check();
  await dialog.getByRole('button', { name: 'Guardar equipos', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await page.reload();
  await page.getByRole('button', { name: 'Gestionar', exact: true }).click();
  await expect(dialog.locator('.team-editor > section')).toHaveCount(2);
  await expect(dialog.getByText('2 integrantes', { exact: true })).toHaveCount(2);
  expect(errors).toEqual([]);
});

test('Google: revisión administrativa, grupo obligatorio y alta aprobada', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.getByLabel('Correo electrónico').fill('admin@erronk2d.test');
  await page.getByLabel('Contraseña', { exact: true }).fill('incorrecta');
  await page.getByRole('button', { name: 'Entrar a Erronk2D' }).click();
  await expect(page.getByRole('alert')).toContainText('El correo o la contraseña no son correctos.');
  await login(page);
  await page.goto('/setup');
  await page.getByRole('link', { name: 'Solicitudes', exact: true }).click();
  await page.getByRole('button', { name: 'Revisar solicitud', exact: true }).click();
  const dialog = page.getByRole('dialog');
  const role = dialog.getByRole('combobox', { name: 'Rol', exact: true });
  const classroom = dialog.getByRole('combobox', { name: 'Grupo', exact: true });
  await expect(classroom).toHaveAttribute('required', '');
  await expect(classroom).toHaveValue('');
  await role.selectOption('teacher');
  await expect(classroom).toHaveCount(0);
  await role.selectOption('student');
  await classroom.selectOption({ label: '2DAW-A' });
  await dialog.getByRole('button', { name: 'Aprobar cuenta', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.getByText('No hay solicitudes pendientes.')).toBeVisible();
  await page.getByRole('link', { name: 'Estudiante', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'browser-google@example.test' })).toContainText('2DAW-A');
  expect(errors).toEqual([]);
});

test('grupos: miembro gestiona matrículas, módulos y evaluaciones desde la tarjeta', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page, 'profesor2@erronk2d.test');
  await page.goto('/setup/classrooms');
  const group = page.locator('.group-card').filter({ has: page.getByRole('heading', { name: '2DAW-A', exact: true }) });
  await expect(group.getByRole('button', { name: 'Editar grupo', exact: true })).toHaveCount(0);
  await group.locator('summary').filter({ hasText: 'Estudiantes' }).click();
  const student = group.locator('.breakdown-row').filter({ has: page.getByText('alumno1@erronk2d.test', { exact: true }) });
  await student.getByRole('button', { name: 'Desmatricular a Ainhoa Agirre', exact: true }).click();
  await expect(student).toHaveCount(0);
  await group.getByLabel('Correo del estudiante').fill('alumno1@erronk2d.test');
  await group.getByRole('button', { name: 'Matricular', exact: true }).click();
  await expect(student).toBeVisible();
  await group.getByRole('button', { name: 'Quitar PROG', exact: true }).click();
  await expect(group.getByRole('button', { name: 'Quitar PROG', exact: true })).toHaveCount(0);
  await expect(group.getByText('Retirados: PROG.', { exact: true })).toBeVisible();
  await page.goto('/reports');
  await expect(page.getByRole('columnheader', { name: '1.ª Evaluación', exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Módulo', exact: true }).selectOption('PROG');
  await expect(page.getByRole('combobox', { name: 'Módulo', exact: true })).toHaveValue('PROG');
  await expect(page.locator('tbody tr').first()).toContainText('PROG');
  await page.goto('/setup/classrooms');
  await expect(group.getByRole('button', { name: 'Quitar PROG', exact: true })).toHaveCount(0);
  await group.getByRole('combobox', { name: 'Añadir módulo', exact: true }).selectOption({ label: 'PROG · Programación' });
  await group.getByRole('button', { name: 'Añadir', exact: true }).click();
  await expect(group.getByRole('button', { name: 'Quitar PROG', exact: true })).toBeVisible();
  await group.getByRole('button', { name: 'Configurar evaluaciones', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByLabel('Evaluación 1', { exact: true })).toHaveAttribute('readonly', '');
  await expect(dialog.getByRole('button', { name: 'Quitar evaluación 1', exact: true })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Añadir evaluación', exact: true }).click();
  await dialog.getByLabel('Evaluación 4', { exact: true }).fill('Evaluación adicional');
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(group.getByText('Evaluación adicional', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/groups-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Organización', exact: true }).click();
  await group.getByRole('button', { name: 'Configurar evaluaciones', exact: true }).click();
  await expect(dialog.getByLabel('Evaluación 1', { exact: true })).toHaveValue('1.ª Evaluación');
  await expect(dialog.getByLabel('Evaluación 4', { exact: true })).toHaveValue('Evaluación adicional');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/group-periods-mobile.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Quitar evaluación 4', exact: true }).click();
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(group.getByText('Evaluación adicional', { exact: true })).toHaveCount(0);
  await group.locator('summary').filter({ hasText: 'Estudiantes' }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/groups-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('curso académico: primer acceso, grupo propio, cambio entre pestañas y preferencia persistente', async ({ page }) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await page.goto('/setup/courses');
  const previousYear = await page.getByLabel('Curso académico activo').inputValue();
  await page.getByRole('button', { name: 'Curso', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Nombre', { exact: true }).fill('2027-28 · navegador');
  await page.getByRole('dialog').getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await login(page, 'profesor1@erronk2d.test');
  await expect(page.getByLabel('Curso académico activo').locator('option:checked')).toHaveText('2027-28 · navegador');
  await expect(page.locator('.challenge-card')).toHaveCount(0);
  await page.goto('/setup/classrooms');
  await page.getByRole('button', { name: 'Grupo', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Nombre', { exact: true }).fill('142GA');
  await page.getByRole('dialog').getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(page.getByRole('heading', { name: '142GA', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Responsables', exact: true })).toHaveCount(4);
  await page.getByRole('button', { name: 'Responsables', exact: true }).first().click();
  await page.getByRole('dialog').getByLabel('Ane Etxeberria', { exact: true }).check();
  await page.getByRole('dialog').getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const staleTab = await page.context().newPage();
  await staleTab.goto('/setup/classrooms');
  await staleTab.getByRole('button', { name: 'Grupo', exact: true }).click();
  await staleTab.getByRole('dialog').getByLabel('Nombre', { exact: true }).fill('Contexto caducado');
  await page.getByLabel('Curso académico activo').selectOption(previousYear);
  await expect(page.locator('.challenge-card')).not.toHaveCount(0);
  await staleTab.getByRole('dialog').getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(staleTab.getByRole('alert').filter({ hasText: /curso/i })).toBeVisible();
  await expect(staleTab.getByRole('dialog').getByLabel('Nombre', { exact: true })).toHaveValue('Contexto caducado');
  await staleTab.close();
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await login(page, 'profesor1@erronk2d.test');
  await expect(page.getByLabel('Curso académico activo')).toHaveValue(previousYear);
  await page.getByLabel('Curso académico activo').selectOption({ label: '2027-28 · navegador' });
  await page.goto('/setup/classrooms');
  await expect(page.getByRole('heading', { name: '142GA', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '2DAW-A', exact: true })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/academic-context.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('curso cerrado: histórico del estudiante y bloqueo de edición del profesorado', async ({ page }) => {
  await login(page);
  await page.goto('/setup/courses');
  const oldYearCard = page.locator('.setup-grid > section').filter({ has: page.getByRole('heading', { name: 'Curso revisado en navegador', exact: true }) });
  await oldYearCard.getByRole('button', { name: 'Cerrar curso', exact: true }).click();
  await expect(oldYearCard.getByRole('button', { name: 'Reabrir curso', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await login(page, 'alumno1@erronk2d.test');
  await expect(page.getByLabel('Curso académico activo').locator('option')).toHaveCount(1);
  await expect(page.getByRole('status').filter({ hasText: 'Solo lectura' })).toBeVisible();
  await page.locator('.challenge-card').filter({ has: page.locator('.badge.published') }).click();
  await expect(page.getByRole('heading', { name: 'Tus resultados publicados' })).toBeVisible();
  await expect(page.locator('.student-rubric button').first()).toBeDisabled();
  await page.screenshot({ path: 'test-results/academic-history.png', fullPage: true });
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await login(page, 'profesor1@erronk2d.test');
  await page.getByLabel('Curso académico activo').selectOption({ label: 'Curso revisado en navegador · Cerrado' });
  await expect(page.getByRole('button', { name: 'Nuevo reto', exact: true })).toHaveCount(0);
  await page.goto('/setup/classrooms');
  await expect(page.getByRole('heading', { name: '2DAW-A', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Editar grupo', exact: true })).toHaveCount(0);
});
