import { test, expect, type Page } from '@playwright/test';
const password = process.env.TEST_BROWSER_PASSWORD;
if (!password) throw new Error('Falta la contraseña del entorno de navegador aislado.');

test.beforeEach(async ({ page }) => {
  const response = await page.goto('/login');
  expect(response?.ok()).toBe(true);
  const html = await response!.text();
  const data = await page.evaluate(html => {
    const document = new DOMParser().parseFromString(html, 'text/html');
    return JSON.parse(document.querySelector('script[data-page="app"]')!.textContent!);
  }, html);
  expect(data.props.test_environment, 'La instancia debe identificarse como testing antes de enviar credenciales o escribir').toBe(true);
});

async function login(page: Page, email = 'admin@erronk2d.test') {
  await page.goto('/login');
  await page.getByLabel('Correo electrónico').fill(email);
  await page.getByLabel('Contraseña', { exact: true }).fill(password!);
  await page.getByRole('button', { name: 'Entrar a Erronk2D' }).click();
  await expect(page.getByRole('heading', { name: 'Tus retos.' })).toBeVisible();
}

test('creación de reto: rúbricas compatibles y validación sin perder el formulario', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await page.getByRole('button', { name: 'Nuevo reto', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Nombre del reto').fill('Regresión de creación');
  await dialog.getByLabel('Descripción', { exact: true }).fill('Conservar este texto al validar.');
  await dialog.getByRole('combobox', { name: 'Evaluación', exact: true }).selectOption({ label: '1.ª Evaluación' });
  const modules = dialog.locator('fieldset').getByRole('checkbox');
  const teamRubric = dialog.getByRole('combobox', { name: 'Rúbrica del reto', exact: true });
  const teamOption = teamRubric.getByRole('option', { name: /Proyecto web/ });
  await expect(teamOption).toHaveJSProperty('disabled', true);
  for (const module of await modules.all()) await module.check();
  await expect(teamOption).toHaveJSProperty('disabled', false);
  await teamRubric.selectOption({ label: 'Proyecto web · Rúbrica de equipo' });
  await modules.last().uncheck();
  await expect(teamRubric).toHaveValue('');
  await expect(teamOption).toHaveJSProperty('disabled', true);
  await modules.last().check();
  await teamRubric.selectOption({ label: 'Proyecto web · Rúbrica de equipo' });
  await dialog.getByRole('combobox', { name: 'Rúbrica transversal', exact: true }).selectOption({ label: 'Aprender en equipo · Transversales' });

  await page.route('**/challenges', async route => {
    const data = route.request().postDataJSON();
    await route.continue({ postData: JSON.stringify({ ...data, module_ids: data.module_ids.slice(0, -1) }) });
  });
  await dialog.getByRole('button', { name: 'Crear reto', exact: true }).click();
  await expect(dialog.getByText('La rúbrica incluye criterios de módulos que no participan.', { exact: false })).toBeVisible();
  await expect(dialog.getByLabel('Nombre del reto')).toHaveValue('Regresión de creación');
  await expect(dialog.getByLabel('Descripción', { exact: true })).toHaveValue('Conservar este texto al validar.');
  await page.unroute('**/challenges');
  await dialog.getByRole('button', { name: 'Crear reto', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Regresión de creación', exact: true })).toBeVisible();
  await expect(dialog).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('profesorado: matriz, teclado, configuración y seguimiento', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await login(page);
  await page.screenshot({ path: 'test-results/dashboard.png', fullPage: true });
  await page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Una web para nuestra comunidad' }) }).click();
  await page.getByRole('link', { name: 'Evaluación', exact: true }).click();
  await expect(page.locator('.matrix tbody tr')).toHaveCount(20);
  await expect(page.getByLabel('Progreso por tipo de evaluación')).toHaveCount(0);
  const first = page.getByLabel('Examen PROG de Ainhoa Agirre', { exact: true });
  const second = page.getByLabel('Examen DWEC de Ainhoa Agirre', { exact: true });
  const oldFirst = await first.inputValue(), oldSecond = await second.inputValue();
  await page.route(page.url().split('?')[0], async route => {
    if (route.request().method() === 'POST') await new Promise(resolve => setTimeout(resolve, 350));
    await route.continue();
  });
  try {
    await first.fill('7,12');
    await first.press('Tab');
    await second.fill('8,43');
    await second.press('Enter');
    await expect(page.getByRole('tabpanel', { name: 'Evaluación', exact: true }).getByText('Cambios guardados', { exact: true })).toBeVisible();
    await page.reload();
    await expect(first).toHaveValue('7.1200');
    await expect(second).toHaveValue('8.4300');
    await page.getByRole('button', { name: 'Ev. transversales', exact: true }).click();
    await expect(page.getByRole('combobox', { name: 'Estudiante a evaluar' }).locator('option')).toHaveCount(20);
    await expect(page.locator('.rubric-assessment tbody tr')).toHaveCount(4);
    await page.getByRole('button', { name: 'Atrás', exact: true }).click();
    await page.getByRole('tab', { name: 'Configuración', exact: true }).click();
    await expect(page.getByRole('tabpanel', { name: 'Configuración', exact: true }).getByText('Defensas por módulo')).toBeVisible();
    await page.getByRole('tab', { name: 'Evaluación', exact: true }).click();
    await page.screenshot({ path: 'test-results/matrix.png', fullPage: true });
  } finally {
    await first.fill(String(Number(oldFirst))); await first.press('Tab');
    await second.fill(String(Number(oldSecond))); await second.press('Enter');
    await expect(page.getByRole('tabpanel', { name: 'Evaluación', exact: true }).getByText('Cambios guardados', { exact: true })).toBeVisible();
  }
  await page.goto('/reports');
  await expect(page.getByRole('heading', { name: 'Cada Evaluación cuenta.' })).toBeVisible();
  await expect(page.locator('tbody tr')).toHaveCount(80);
  await page.goto('/setup');
  await page.getByRole('link', { name: 'Rúbricas', exact: true }).click();
  await page.getByRole('button', { name: 'Duplicar rúbrica' }).first().click();
  await expect(page.getByRole('heading', { name: /\(copia\)/ }).first()).toBeVisible();
  expect(errors).toEqual([]);
});

test('alumnado: autoevaluación, compañeros, resultado propio y móvil', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await login(page, 'alumno1@erronk2d.test');
  await page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Una web para nuestra comunidad' }) }).click();
  await expect(page.getByRole('button', { name: 'Mi autoevaluación', exact: true })).toBeVisible();
  await expect(page.locator('.person-tabs button')).toHaveCount(4);
  await expect(page.getByRole('heading', { name: 'Tus resultados publicados' })).toHaveCount(0);
  const chosen = page.locator('.student-rubric').first().locator('button.chosen');
  await chosen.click();
  await expect(page.getByRole('status')).toHaveText('Evaluación guardada');
  await page.goto('/');
  await page.locator('.challenge-card').filter({ has: page.locator('.badge.published') }).click();
  await expect(page.getByRole('heading', { name: 'Tus resultados publicados' })).toBeVisible();
  await expect(page.locator('.module-breakdowns section')).toHaveCount(4);
  await page.screenshot({ path: 'test-results/student-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});


test('equipos: recuperar participantes y asignar estudiantes con búsqueda y orden alfabético', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Reto vacío para pruebas' }) }).click();
  await page.getByRole('link', { name: 'Estudiantes y Equipos', exact: true }).click();
  const dialog = page.getByRole('tabpanel', { name: 'Estudiantes y Equipos', exact: true });
  await expect(dialog.getByText('Este reto no tiene estudiantes.', { exact: false })).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Guardar equipos', exact: true })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Incorporar estudiantes del grupo', exact: true }).click();
  const teams = dialog.locator('.team-editor > section');
  await teams.first().getByRole('button', { name: 'Añadir estudiantes', exact: true }).click();
  const firstTeamOptions = teams.first().locator('.team-student-option');
  await expect(firstTeamOptions.first()).toBeVisible();
  expect((await teams.first().locator('.team-student-option > span:first-child').allTextContents()).slice(0, 3).map(name => name.trim())).toEqual(['Ainhoa Agirre', 'Aitor Fernández', 'Alaia Martínez']);
  const firstTeamSearch = teams.first().getByRole('searchbox', { name: 'Buscar estudiantes disponibles para el equipo 1' });
  await firstTeamSearch.fill('ainhoa');
  await expect(firstTeamOptions).toHaveCount(1);
  await firstTeamOptions.filter({ hasText: 'Ainhoa Agirre' }).click();
  await firstTeamSearch.fill('fernandez');
  await expect(firstTeamOptions).toHaveCount(1);
  await firstTeamOptions.filter({ hasText: 'Aitor Fernández' }).click();
  await expect(teams.first().locator('.team-members li')).toHaveCount(2);
  await teams.first().locator('.team-members button').first().click();
  await expect(teams.first().locator('.team-members li')).toHaveCount(1);
  await expect(dialog.getByRole('button', { name: 'Guardar equipos', exact: true })).toBeDisabled();
  await firstTeamSearch.fill('ainhoa');
  await expect(firstTeamOptions).toHaveCount(1);
  await firstTeamOptions.filter({ hasText: 'Ainhoa Agirre' }).click();
  await expect(teams.first().locator('.team-members li')).toHaveCount(2);
  await teams.first().getByRole('button', { name: 'Cerrar selector', exact: true }).click();
  await dialog.getByRole('button', { name: 'Añadir equipo', exact: true }).click();
  await teams.nth(1).getByRole('button', { name: 'Añadir estudiantes', exact: true }).click();
  const secondTeamOptions = teams.nth(1).locator('.team-student-option');
  await expect(secondTeamOptions.filter({ hasText: 'Ainhoa Agirre' })).toHaveCount(0);
  await expect(secondTeamOptions.filter({ hasText: 'Aitor Fernández' })).toHaveCount(0);
  const secondTeamSearch = teams.nth(1).getByRole('searchbox', { name: 'Buscar estudiantes disponibles para el equipo 2' });
  await secondTeamSearch.fill('alaia');
  await secondTeamOptions.filter({ hasText: 'Alaia Martínez' }).click();
  await secondTeamSearch.fill('ander');
  await secondTeamOptions.filter({ hasText: 'Ander García' }).click();
  await dialog.getByRole('button', { name: 'Guardar equipos', exact: true }).click();
  await expect(dialog.getByRole('status')).toHaveText('Cambios guardados');
  await page.reload();
  await page.getByRole('tab', { name: 'Estudiantes y Equipos', exact: true }).click();
  await expect(dialog.locator('.team-editor > section')).toHaveCount(2);
  await expect(dialog.locator('.team-roster-heading b')).toHaveText(['2/5', '2/5']);
  await expect(dialog.locator('.team-members li')).toHaveCount(4);
  await page.setViewportSize({ width: 390, height: 844 });
  await teams.first().getByRole('button', { name: 'Añadir estudiantes', exact: true }).click();
  await expect(teams.first().locator('.team-student-option').first()).toBeVisible();
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/team-picker-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('grupos: miembro gestiona matrículas, módulos y evaluaciones desde la tarjeta', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page, 'profesor2@erronk2d.test');
  await page.goto('/setup/classrooms');
  const group = page.locator('.group-card').filter({ has: page.getByRole('heading', { name: '2DAW-A', exact: true }) });
  await expect(group.getByRole('button', { name: 'Editar grupo', exact: true })).toHaveCount(0);
  await group.locator('summary').filter({ hasText: 'Estudiantes' }).click();
  const student = group.locator('.breakdown-row').filter({ has: page.getByText('alumno1@erronk2d.test', { exact: true }) });
  await student.getByRole('button', { name: 'Desmatricular a Ainhoa Agirre', exact: true }).click();
  await expect(student).toHaveCount(0);
  await group.getByLabel('Correo del estudiante').fill('alumno1@erronk2d.test');
  await group.getByRole('button', { name: 'Matricular', exact: true }).click();
  await expect(student).toBeVisible();
  await group.getByRole('button', { name: 'Quitar PROG', exact: true }).click();
  await expect(group.getByRole('button', { name: 'Quitar PROG', exact: true })).toHaveCount(0);
  await expect(group.getByText('Retirados: PROG.', { exact: true })).toBeVisible();
  await page.goto('/reports');
  await expect(page.getByRole('columnheader', { name: '1.ª Evaluación', exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Módulo', exact: true }).selectOption('PROG');
  await expect(page.getByRole('combobox', { name: 'Módulo', exact: true })).toHaveValue('PROG');
  await expect(page.locator('tbody tr').first()).toContainText('PROG');
  await page.goto('/setup/classrooms');
  await expect(group.getByRole('button', { name: 'Quitar PROG', exact: true })).toHaveCount(0);
  await group.getByRole('combobox', { name: 'Añadir módulo', exact: true }).selectOption({ label: 'PROG · Programación' });
  await group.getByRole('button', { name: 'Añadir', exact: true }).click();
  await expect(group.getByRole('button', { name: 'Quitar PROG', exact: true })).toBeVisible();
  await group.getByRole('button', { name: 'Configurar evaluaciones', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByLabel('Evaluación 1', { exact: true })).toHaveAttribute('readonly', '');
  await expect(dialog.getByRole('button', { name: 'Quitar evaluación 1', exact: true })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Añadir evaluación', exact: true }).click();
  await dialog.getByLabel('Evaluación 4', { exact: true }).fill('Evaluación adicional');
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(group.getByText('Evaluación adicional', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/groups-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Organización', exact: true }).click();
  await group.getByRole('button', { name: 'Configurar evaluaciones', exact: true }).click();
  await expect(dialog.getByLabel('Evaluación 1', { exact: true })).toHaveValue('1.ª Evaluación');
  await expect(dialog.getByLabel('Evaluación 4', { exact: true })).toHaveValue('Evaluación adicional');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/group-periods-mobile.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Quitar evaluación 4', exact: true }).click();
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(group.getByText('Evaluación adicional', { exact: true })).toHaveCount(0);
  await group.locator('summary').filter({ hasText: 'Estudiantes' }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/groups-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('curso académico: primer acceso, grupo propio, cambio entre pestañas y preferencia persistente', async ({ page }) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await page.goto('/setup/courses');
  const previousYear = await page.getByLabel('Curso académico activo').inputValue();
  await page.getByRole('button', { name: 'Curso', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Nombre', { exact: true }).fill('2027-28 · navegador');
  await page.getByRole('dialog').getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await login(page, 'profesor1@erronk2d.test');
  await expect(page.getByLabel('Curso académico activo').locator('option:checked')).toHaveText('2027-28 · navegador');
  await expect(page.locator('.challenge-card')).toHaveCount(0);
  await page.goto('/setup/classrooms');
  await page.getByRole('button', { name: 'Grupo', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Nombre', { exact: true }).fill('142GA');
  await page.getByRole('dialog').getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(page.getByRole('heading', { name: '142GA', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Responsables', exact: true })).toHaveCount(4);
  await page.getByRole('button', { name: 'Responsables', exact: true }).first().click();
  await page.getByRole('dialog').getByLabel('Ane Etxeberria', { exact: true }).check();
  await page.getByRole('dialog').getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const staleTab = await page.context().newPage();
  await staleTab.goto('/setup/classrooms');
  await staleTab.getByRole('button', { name: 'Grupo', exact: true }).click();
  await staleTab.getByRole('dialog').getByLabel('Nombre', { exact: true }).fill('Contexto caducado');
  await page.getByLabel('Curso académico activo').selectOption(previousYear);
  await expect(page.locator('.challenge-card')).not.toHaveCount(0);
  await staleTab.getByRole('dialog').getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(staleTab.getByRole('alert').filter({ hasText: /curso/i })).toBeVisible();
  await expect(staleTab.getByRole('dialog').getByLabel('Nombre', { exact: true })).toHaveValue('Contexto caducado');
  await staleTab.close();
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await login(page, 'profesor1@erronk2d.test');
  await expect(page.getByLabel('Curso académico activo')).toHaveValue(previousYear);
  await page.getByLabel('Curso académico activo').selectOption({ label: '2027-28 · navegador' });
  await page.goto('/setup/classrooms');
  await expect(page.getByRole('heading', { name: '142GA', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '2DAW-A', exact: true })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/academic-context.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('curso cerrado: histórico del estudiante y bloqueo de edición del profesorado', async ({ page }) => {
  await login(page);
  await page.goto('/setup/courses');
  const oldYearCard = page.locator('.setup-grid > section').filter({ has: page.getByRole('heading', { name: 'Curso revisado en navegador', exact: true }) });
  await oldYearCard.getByRole('button', { name: 'Cerrar curso', exact: true }).click();
  await expect(oldYearCard.getByRole('button', { name: 'Reabrir curso', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await login(page, 'alumno1@erronk2d.test');
  await expect(page.getByLabel('Curso académico activo').locator('option')).toHaveCount(1);
  await expect(page.getByRole('status').filter({ hasText: 'Solo lectura' })).toBeVisible();
  await page.locator('.challenge-card').filter({ has: page.locator('.badge.published') }).click();
  await expect(page.getByRole('heading', { name: 'Tus resultados publicados' })).toBeVisible();
  await expect(page.locator('.student-rubric .rubric-choice').first()).toBeDisabled();
  await page.screenshot({ path: 'test-results/academic-history.png', fullPage: true });
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await login(page, 'profesor1@erronk2d.test');
  await page.getByLabel('Curso académico activo').selectOption({ label: 'Curso revisado en navegador · Cerrado' });
  await expect(page.getByRole('button', { name: 'Nuevo reto', exact: true })).toHaveCount(0);
  await page.goto('/setup/classrooms');
  await expect(page.getByRole('heading', { name: '2DAW-A', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Editar grupo', exact: true })).toHaveCount(0);
});

test('catálogo: tablas, filtros, orden y módulos libres por ciclo', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await expect(page.locator('.overview-grid')).toHaveCount(0);
  const suffix = Date.now().toString();
  const cycleName = `Ciclo catálogo ${suffix}`;
  await page.goto('/setup/cycles');
  await page.getByRole('button', { name: 'Ciclo', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Nombre', { exact: true }).fill(cycleName);
  await dialog.getByLabel('Código', { exact: true }).fill(`C${suffix}`);
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const cycleRow = page.getByRole('table', { name: 'Ciclos', exact: true }).getByRole('row').filter({ hasText: cycleName });
  await expect(cycleRow).toBeVisible();
  await page.goto('/setup/modules');
  for (const name of ['Álgebra', 'Zoología']) {
    await page.getByRole('button', { name: 'Módulo', exact: true }).click();
    await dialog.getByLabel('Nombre', { exact: true }).fill(`${name} ${suffix}`);
    await dialog.getByLabel('Código', { exact: true }).fill(`${name[0]}${suffix}`);
    await dialog.getByRole('combobox', { name: 'Ciclo', exact: true }).selectOption('');
    await dialog.getByRole('combobox', { name: 'Curso / nivel', exact: true }).selectOption('1');
    await dialog.getByRole('button', { name: 'Guardar', exact: true }).click();
    await expect(dialog).toHaveCount(0);
  }
  await page.getByRole('combobox', { name: 'Ciclo', exact: true }).selectOption('unassigned');
  await page.getByRole('combobox', { name: 'Curso', exact: true }).selectOption('1');
  const table = page.getByRole('table', { name: 'Módulos', exact: true });
  const names = () => table.locator('tbody tr').filter({ hasText: suffix }).locator('td:nth-child(2)').allTextContents();
  expect(await names()).toEqual([`Álgebra ${suffix}`, `Zoología ${suffix}`]);
  await table.getByRole('button', { name: 'Nombre' }).click();
  expect(await names()).toEqual([`Zoología ${suffix}`, `Álgebra ${suffix}`]);
  await page.getByRole('combobox', { name: 'Curso', exact: true }).selectOption('4');
  await expect(table.getByText('No hay módulos que coincidan con los filtros.')).toBeVisible();
  await page.goto('/setup/cycles');
  await cycleRow.getByRole('button', { name: 'Ver módulos' }).click();
  await dialog.getByLabel('Buscar módulos por nombre').fill(`Algebra ${suffix}`);
  await dialog.getByRole('combobox', { name: 'Curso de destino', exact: true }).selectOption('2');
  await dialog.getByRole('button', { name: `Añadir Álgebra ${suffix}`, exact: true }).click();
  await expect(dialog.getByRole('table').getByText(`Álgebra ${suffix}`)).toBeVisible();
  await expect(dialog.getByRole('button', { name: `Añadir Álgebra ${suffix}`, exact: true })).toHaveCount(0);
  await page.reload();
  await cycleRow.getByRole('button', { name: 'Ver módulos' }).click();
  await expect(dialog.getByRole('table').getByText(`Álgebra ${suffix}`)).toBeVisible();
  await dialog.getByRole('button', { name: `Quitar Álgebra ${suffix}`, exact: true }).click();
  await expect(dialog.getByRole('table').getByText('Este ciclo todavía no incluye módulos.')).toBeVisible();
  await dialog.getByLabel('Buscar módulos por nombre').fill(`Algebra ${suffix}`);
  await dialog.getByRole('combobox', { name: 'Curso de destino', exact: true }).selectOption('2');
  await dialog.getByRole('button', { name: `Añadir Álgebra ${suffix}`, exact: true }).click();
  await expect(dialog.getByRole('table').getByText(`Álgebra ${suffix}`)).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/cycle-modules-mobile.png', fullPage: true });
  await page.keyboard.press('Escape');
  await page.goto('/setup/modules');
  await page.getByRole('combobox', { name: 'Ciclo', exact: true }).selectOption({ label: cycleName });
  await page.getByRole('combobox', { name: 'Curso', exact: true }).selectOption('2');
  await expect(table.locator('tbody tr')).toHaveCount(1);
  await expect(table.getByText(`Álgebra ${suffix}`)).toBeVisible();
  await page.screenshot({ path: 'test-results/modules-table-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});
