<script setup lang="ts">
import { computed, ref, watch } from 'vue'; import { Head, router, useForm, usePage } from '@inertiajs/vue3';
import { Plus, Pencil, Copy, ArrowUp, ArrowDown, X, Upload } from 'lucide-vue-next';
import RegistrationRequests from '../components/RegistrationRequests.vue';
import Layout from '../components/Layout.vue'; import Modal from '../components/Modal.vue'; import { api, permission } from '../lib';
const props=defineProps<{section:string;title:string;years:any[];classrooms:any[];users:any[];rubrics:any[];permissions:string[];registrations:any[];teachers:any[];cycles:any[];modules:any[]}>();
const tab=computed(()=>({teachers:'teacher',students:'student'} as Record<string,string>)[props.section]??props.section),modal=ref(''),entity=ref(''),form=useForm<Record<string,any>>({}),periodText=ref('1.ª Evaluación\n2.ª Evaluación\n3.ª Evaluación');
watch(()=>props.section,()=>{modal.value='';form.clearErrors()});
const teachers=computed(()=>props.teachers);const modules=computed(()=>props.modules);
const year=computed(()=>(usePage().props.academic as any)?.year);const canWork=computed(()=>!!year.value?.is_open);
const rubricModules=computed(()=>modules.value.filter(m=>m.cycle_id===Number(form.cycle_id)&&m.level===Number(form.level)));
const responsibilityClass=computed(()=>props.classrooms.find(c=>c.id===Number(form.classroom_id)));
const isAdmin=(usePage().props.auth as any).role==='admin';
const formKeys=ref<string[]>([]);
const names:Record<string,string>={year:'Curso académico',cycle:'Ciclo',enrollment:'Matrícula',responsibility:'Responsables de módulo',classroom:'Clase',student:'Estudiante',teacher:'Profesor',module:'Módulo',rubric:'Rúbrica'};
function open(type:string,data?:any){entity.value=type;form.clearErrors();const initial:Record<string,any>={name:'',...(data?JSON.parse(JSON.stringify(data)):{})};
if(type==='year')periodText.value=data?.periods.map((p:any)=>p.name).join('\n')??'1.ª Evaluación\n2.ª Evaluación\n3.ª Evaluación';
if(['classroom','module'].includes(type)){initial.cycle_id=data?.cycle_id??props.cycles[0]?.id??'';initial.level=data?.level??2}
if(type==='classroom'){initial.user_ids=data?.users?.map((u:any)=>u.id)??[];initial.owner_id=data?.owner_id??(usePage().props.auth as any).id}
if(['student','teacher'].includes(type)){initial.email=data?.email??'';initial.password='';initial.active=data?.active??true;delete initial.permissions}
if(type==='student')initial.classroom_id='';
if(['module','cycle'].includes(type))initial.code=data?.code??'';
if(type==='enrollment'){initial.classroom_id=data?.classroom_id??props.classrooms[0]?.id??'';initial.email=data?.email??'';initial.active=true}
if(type==='rubric'){initial.kind=data?.kind??'team';initial.items=data?.items??[newItem()];initial.cycle_id=data?.cycle_id??'';initial.level=data?.level??'';initial.shared_user_ids=data?.shared_users?.map((u:any)=>u.id)??[]}
formKeys.value.forEach(k=>delete (form as any)[k]);Object.assign(form,initial);formKeys.value=Object.keys(initial);modal.value='edit'}
function copyRubric(id:number){router.post('/setup/rubric-copy',{id})}
function yearStatus(y:any){router.post('/setup/year-status',{id:y.id,is_open:!y.is_open})}
function endEnrollment(u:any,e:any){router.post('/setup/enrollment',{email:u.email,classroom_id:e.classroom_id,active:false})}
const foundStudent=ref<any>(null),lookupError=ref('');
async function lookup(){foundStudent.value=null;lookupError.value='';try{foundStudent.value=(await api('/students/lookup',{email:form.email,classroom_id:form.classroom_id})).student;if(!foundStudent.value)lookupError.value='No se ha encontrado un estudiante activo con ese correo.'}catch(e){lookupError.value=(e as Error).message}}
function newItem(){return {key:`c_${Math.random().toString(36).slice(2,10)}`,name:'',description:'',module_id:null,weight:'1',levels:[{score:'4',description:'Necesita acompañamiento'},{score:'6',description:'En desarrollo'},{score:'8',description:'Desempeño autónomo'},{score:'10',description:'Dominio excelente'}]}}
function submit(){form.transform(()=>{const data=Object.fromEntries(formKeys.value.map(k=>[k,form[k]]));if(entity.value==='year')data.periods=periodText.value.split('\n').map(p=>p.trim()).filter(Boolean);return data});form.post(`/setup/${entity.value}`,{onSuccess:()=>{modal.value='';router.reload()}})}
function move(index:number,by:number){const target=index+by;if(target<0||target>=form.items.length)return;[form.items[index],form.items[target]]=[form.items[target],form.items[index]]}
const importCycle=ref(''),importLevel=ref(2);
const importKind=ref('student'),importClass=ref(''),file=ref<File|null>(null),importResult=ref<any>(null),importError=ref(''),importBusy=ref(false);
async function importFile(commit=false){if(!file.value)return;importBusy.value=true;importError.value='';try{const data=new FormData();data.append('kind',importKind.value);data.append('commit',commit?'1':'0');data.append('file',file.value);if(importKind.value==='student'&&importClass.value)data.append('classroom_id',importClass.value);if(importKind.value==='module'){data.append('cycle_id',importCycle.value);data.append('level',String(importLevel.value))}importResult.value=await api('/imports',data);if(importResult.value.committed)router.reload()}catch(e){importError.value=(e as Error).message}finally{importBusy.value=false}}
</script>
<template><Layout><Head :title="title"/><div class="topline"><span>Organización / {{title}}</span><span>BASES PARA UN BUEN RETO</span></div><header class="page-heading"><div><p class="eyebrow">ORGANIZACIÓN DEL CENTRO</p><h1>{{title}}<span class="accent">.</span></h1><p class="muted">Gestiona esta sección y accede al resto desde el menú Organización.</p></div><button v-if="(isAdmin&&['teacher','modules'].includes(tab))||(tab==='student'&&canWork&&classrooms.length)" class="button" @click="importKind=tab==='modules'?'module':tab;modal='import';importResult=null"><Upload :size="17"/>Importar CSV / Excel</button></header>
<RegistrationRequests v-if="isAdmin&&tab==='registrations'" :registrations="registrations" :classrooms="classrooms"/>
<template v-if="tab==='courses'"><div class="workspace-heading"><h2>Cursos académicos</h2><button v-if="permission('manage_academics')" class="button primary" @click="open('year')"><Plus :size="17"/>Curso</button></div><div class="setup-grid"><section v-for="y in years" class="panel"><div class="actions"><h3>{{y.name}}</h3><span class="badge">{{y.is_open?'Abierto':'Cerrado'}}</span><button class="button small" @click="yearStatus(y)">{{y.is_open?'Cerrar curso':'Reabrir curso'}}</button><button v-if="isAdmin&&y.is_open" class="icon-button" aria-label="Editar curso" @click="open('year',y)"><Pencil :size="16"/></button></div><div class="module-chips"><span v-for="p in y.periods">{{p.name}}</span></div><p class="helper">La nota del curso será la media de estas {{y.periods.length}} Evaluaciones.</p></section></div></template><template v-if="tab==='classrooms'"><div class="workspace-heading"><h2>Clases y matrículas</h2><p v-if="!cycles.length" class="helper">Administración debe configurar primero los ciclos y módulos.</p><button v-if="canWork&&cycles.length" class="button" @click="open('classroom')"><Plus :size="17"/>Clase</button></div><div class="setup-grid"><section v-for="c in classrooms" class="panel"><div class="actions"><h3>{{c.name}}</h3><span class="muted">{{c.cycle_name}} · {{c.level}}.º</span><button v-if="canWork&&c.can_manage" class="icon-button" aria-label="Editar clase" @click="open('classroom',c)"><Pencil :size="16"/></button></div><p>{{c.students.length}} estudiantes · {{c.modules.length}} módulos</p><div class="module-chips"><span v-for="m in c.modules">{{m.code}}</span></div><p class="helper">Profesorado: {{c.users.map((u:any)=>u.name).join(', ')}}</p><div v-for="m in c.modules" class="breakdown-row"><span>{{m.code}} · {{m.teachers.map((t:any)=>t.name).join(', ')||'Sin responsables'}}</span><button v-if="canWork&&c.can_manage" class="button small" @click="open('responsibility',{classroom_id:c.id,module_id:m.id,teacher_ids:m.teachers.map((t:any)=>t.id)})">Responsables</button></div></section></div></template>
<template v-if="tab==='cycles'"><div class="workspace-heading"><h2>Ciclos de Formación Profesional</h2><button class="button primary" @click="open('cycle')"><Plus :size="17"/>Ciclo</button></div><div class="setup-grid"><section v-for="c in cycles" class="panel"><span class="module-chip">{{c.code}}</span><h3>{{c.name}}</h3><button class="button" @click="open('cycle',c)">Editar ciclo</button></section></div></template>
<template v-if="tab==='teacher'||tab==='student'"><div class="workspace-heading"><h2>{{tab==='student'?'Estudiantes':'Profesores'}}</h2><button v-if="tab==='student'&&canWork&&classrooms.length" class="button" @click="foundStudent=null;lookupError='';open('enrollment')">Matricular por correo</button><button v-if="isAdmin||(canWork&&classrooms.length)" class="button primary" @click="open(tab)"><Plus :size="17"/>{{tab==='student'?'Estudiante':'Profesor'}}</button></div><p v-if="tab==='student'&&!classrooms.length" class="notice">Crea una clase en Organización → Clases antes de dar de alta estudiantes.</p><div class="table-scroll"><table><thead><tr><th>NOMBRE</th><th>CORREO</th><th v-if="tab==='student'">CLASE</th><th>ESTADO</th><th></th></tr></thead><tbody><tr v-for="u in users.filter(u=>u.role===tab)" :key="u.id"><td>{{u.name}}</td><td>{{u.email}}</td><td v-if="tab==='student'"><div v-for="e in u.enrollments">{{classrooms.find(c=>c.id===e.classroom_id)?.name}} <small v-if="e.ended_at">(histórico)</small><button v-else-if="canWork" class="button small" @click="endEnrollment(u,e)">Dar de baja</button></div><span v-if="!u.enrollments.length">Sin matrícula en este curso</span></td><td>{{u.active?'Activo':'Desactivado'}}</td><td><button v-if="isAdmin" class="icon-button" :aria-label="`Editar ${u.name}`" @click="open(u.role,u)"><Pencil :size="17"/></button></td></tr></tbody></table></div></template>
<template v-if="tab==='modules'"><div class="workspace-heading"><h2>Catálogo de módulos</h2><button v-if="permission('manage_modules')" class="button primary" @click="open('module')"><Plus :size="17"/>Módulo</button></div><div class="setup-grid"><section v-for="m in modules" class="panel"><div class="actions"><span class="module-chip">{{m.code}}</span><span class="muted">{{m.cycle?.name}} · {{m.level}}.º</span><button v-if="permission('manage_modules')" class="icon-button" aria-label="Editar módulo" @click="open('module',m)"><Pencil :size="17"/></button></div><h3>{{m.name}}</h3><small class="muted">Los responsables se asignan dentro de cada clase.</small></section></div></template>
<template v-if="tab==='rubrics'"><div class="workspace-heading"><div><h2>Biblioteca de rúbricas</h2><p>Reutiliza tus criterios. Cada reto conserva su propia versión.</p></div><button v-if="permission('manage_rubrics')" class="button primary" @click="open('rubric')"><Plus :size="17"/>Rúbrica</button></div><div class="setup-grid"><section v-for="r in rubrics" class="panel"><span class="eyebrow">{{r.kind==='team'?'VALORACIÓN DEL RETO':'COMPETENCIAS TRANSVERSALES'}}</span><h3>{{r.name}}</h3><small class="muted">{{r.owner_id===(usePage().props.auth as any).id?'Propia':'Compartida para usar y copiar'}}</small><p>{{r.items.map((i:any)=>i.name).join(' · ')}}</p><footer class="actions"><span class="muted">{{r.items.length}} criterios</span><button v-if="isAdmin||r.owner_id===(usePage().props.auth as any).id" class="button" @click="open('rubric',r)"><Pencil :size="15"/>Editar</button><button v-if="permission('manage_rubrics')" class="icon-button" aria-label="Duplicar rúbrica" @click="copyRubric(r.id)"><Copy :size="17"/></button></footer></section></div></template>
<Modal v-if="modal==='edit'" :title="`${form.id?'Editar':'Crear'} ${names[entity]}`" :wide="entity==='rubric'||entity==='teacher'" @close="modal=''"><form @submit.prevent="submit" class="form-grid"><label v-if="!['enrollment','responsibility'].includes(entity)" class="span-2">Nombre<input v-model="form.name" required/></label>
<label v-if="entity==='year'" class="span-2">Evaluaciones, una por línea<textarea v-model="periodText" rows="4" :readonly="!!form.periods_locked" required/><small v-if="form.periods_locked" class="helper">Las Evaluaciones se conservan porque tienen retos. Puedes cambiar el nombre del curso.</small></label>
<template v-if="['classroom','module','rubric'].includes(entity)"><label>Ciclo<select v-model="form.cycle_id" :required="entity!=='rubric'" :disabled="!!form.id&&entity!=='rubric'"><option value="">{{entity==='rubric'?'General':'Selecciona'}}</option><option v-for="c in cycles" :value="c.id">{{c.name}}</option></select></label><label>Curso / nivel<select v-model="form.level" :required="entity!=='rubric'" :disabled="!!form.id&&entity!=='rubric'"><option v-if="entity==='rubric'" value="">General</option><option v-for="n in 4" :value="n">{{n}}.º</option></select></label></template>
<template v-if="entity==='classroom'"><p class="helper span-2">Curso académico: {{year?.name}}. La clase tendrá todos los módulos de su ciclo y nivel.</p><label v-if="isAdmin" class="span-2">Propietario<select v-model="form.owner_id"><option v-for="t in teachers" :value="t.id">{{t.name}}</option></select></label><fieldset class="span-2 scroll-list"><legend>Profesores de la clase</legend><label v-for="t in teachers" class="check"><input v-model="form.user_ids" :value="t.id" type="checkbox"/>{{t.name}}</label></fieldset></template>
<template v-if="entity==='responsibility'"><p class="span-2">{{responsibilityClass?.name}} · {{responsibilityClass?.modules.find((m:any)=>m.id===form.module_id)?.name}}</p><fieldset class="span-2"><legend>Profesores responsables</legend><label v-for="t in responsibilityClass?.users" class="check"><input v-model="form.teacher_ids" :value="t.id" type="checkbox"/>{{t.name}}</label></fieldset></template>
<template v-if="entity==='enrollment'"><label class="span-2">Clase<select v-model="form.classroom_id" required><option v-for="c in classrooms" :value="c.id">{{c.name}}</option></select></label><label class="span-2">Correo exacto del estudiante<input v-model="form.email" type="email" required @input="foundStudent=null"/></label><button type="button" class="button span-2" @click="lookup">Buscar estudiante</button><p v-if="foundStudent" class="notice success span-2">{{foundStudent.name}} · {{foundStudent.email}}</p><p v-if="lookupError" class="notice span-2">{{lookupError}}</p><p class="helper span-2">Se añade esta matrícula conservando las demás clases y su histórico.</p></template>
<template v-if="entity==='cycle'"><label class="span-2">Código<input v-model="form.code" required maxlength="30"/></label></template>
<template v-if="['student','teacher'].includes(entity)"><label class="span-2">Correo<input v-model="form.email" type="email" required/></label><label class="span-2">{{form.id?'Nueva contraseña (opcional)':'Contraseña inicial (mínimo 10 caracteres)'}}<input v-model="form.password" type="password" autocomplete="new-password" :required="!form.id" minlength="10"/></label><label v-if="entity==='student'&&canWork" class="span-2">Añadir matrícula en una clase<select v-model="form.classroom_id" :required="!isAdmin"><option value="">{{isAdmin?'Sin añadir matrícula':'Selecciona una clase'}}</option><option v-for="c in classrooms" :value="c.id">{{c.name}}</option></select><small class="helper">La cuenta se conserva entre años. Puede tener varias matrículas.</small></label><label v-if="isAdmin" class="check span-2"><input v-model="form.active" type="checkbox"/>Cuenta activa</label></template>
<template v-if="entity==='module'"><label class="span-2">Código<input v-model="form.code" maxlength="30" required/></label></template>
<template v-if="entity==='rubric'"><label class="span-2">Tipo<select v-model="form.kind"><option value="team">Valoración del reto</option><option value="transversal">Competencias transversales</option></select></label><section v-for="(item,index) in form.items" class="rubric-editor span-2"><div class="actions"><strong>Criterio {{Number(index)+1}}</strong><button type="button" class="icon-button" aria-label="Subir criterio" @click="move(Number(index),-1)"><ArrowUp :size="16"/></button><button type="button" class="icon-button" aria-label="Bajar criterio" @click="move(Number(index),1)"><ArrowDown :size="16"/></button><button type="button" class="icon-button" aria-label="Eliminar criterio" @click="form.items.splice(index,1)"><X :size="16"/></button></div><div class="form-grid"><label>Nombre<input v-model="item.name" required/></label><label>Peso<input v-model="item.weight" inputmode="decimal" required/></label><label class="span-2">Descripción<textarea v-model="item.description" rows="2"/></label><label v-if="form.kind==='team'" class="span-2">Módulo<select v-model="item.module_id"><option :value="null">GENERAL</option><option v-for="m in rubricModules" :value="m.id">{{m.code}} · {{m.name}}</option></select></label></div><div v-for="(level,li) in item.levels" class="level-editor"><label>Nota<input v-model="level.score" inputmode="decimal" required/></label><label>Descripción del nivel<input v-model="level.description" required/></label><button type="button" class="icon-button" aria-label="Quitar nivel" @click="item.levels.splice(li,1)"><X :size="16"/></button></div><button type="button" class="button small" @click="item.levels.push({score:'10',description:''})">Añadir nivel</button></section><button type="button" class="button span-2" @click="form.items.push(newItem())">Añadir criterio</button><fieldset class="span-2 scroll-list"><legend>Compartir para usar y copiar</legend><label v-for="t in teachers.filter(t=>t.id!==(usePage().props.auth as any).id)" class="check"><input v-model="form.shared_user_ids" type="checkbox" :value="t.id"/>{{t.name}}</label></fieldset><p class="helper span-2">Editar esta plantilla no modifica las rúbricas que ya están asignadas a otros retos.</p></template>
<p v-for="e in form.errors" class="notice error span-2" role="alert">{{e}}</p><button class="button primary span-2" :disabled="form.processing||(entity==='student'&&!isAdmin&&(!canWork||!classrooms.length))">Guardar</button></form></Modal>
<Modal v-if="modal==='import'" title="Importar datos" @close="modal=''" wide><div class="form-grid"><label>Tipo<select v-model="importKind" @change="importResult=null"><option value="student">Estudiantes</option><option v-if="isAdmin" value="teacher">Profesores</option><option v-if="isAdmin" value="module">Módulos</option></select></label><label v-if="importKind==='student'">Clase<select v-model="importClass" @change="importResult=null"><option value="">Selecciona una clase</option><option v-for="c in classrooms" :value="c.id">{{c.name}}</option></select></label><template v-if="importKind==='module'"><label>Ciclo<select v-model="importCycle" @change="importResult=null"><option value="">Selecciona</option><option v-for="c in cycles" :value="c.id">{{c.name}}</option></select></label><label>Curso / nivel<select v-model="importLevel" @change="importResult=null"><option v-for="n in 4" :value="n">{{n}}.º</option></select></label></template><label class="span-2">Archivo CSV o XLSX<input type="file" accept=".csv,.xlsx" @change="file=($event.target as HTMLInputElement).files?.[0]??null;importResult=null"/></label></div><p class="helper">Cabeceras: <code>{{importKind==='module'?'name, code':'name, email'}}</code>. Máximo 1.000 filas y 2 MB. Las nuevas cuentas podrán establecer contraseña mediante el enlace de recuperación cuando el correo esté configurado.</p><button class="button" :disabled="!file||importBusy||(importKind==='student'&&!importClass)||(importKind==='module'&&!importCycle)" @click="importFile(false)">Validar y previsualizar</button><p v-if="importError" class="notice error">{{importError}}</p><div v-if="importResult"><p v-if="importResult.classroom">Clase: {{importResult.classroom.name}}</p><p>{{importResult.count}} filas válidas · {{importResult.errors.length}} errores</p><p v-for="e in importResult.errors" class="notice error">Fila {{e.row}}: {{e.message}}</p><table><tbody><tr v-for="row in importResult.preview"><td>{{row.name}}</td><td>{{row.email??row.code}}</td></tr></tbody></table><button v-if="!importResult.errors.length&&!importResult.committed" class="button primary full" :disabled="importBusy" @click="importFile(true)">Confirmar importación</button><p v-if="importResult.committed" class="notice success">Importación completada.</p></div></Modal>
</Layout></template>
