<script setup lang="ts">
import { computed, ref } from 'vue'; import { Head, router, useForm, usePage } from '@inertiajs/vue3';
import { Plus, Pencil, Copy, ArrowUp, ArrowDown, X, Upload } from 'lucide-vue-next';
import RegistrationRequests from '../components/RegistrationRequests.vue';
import Layout from '../components/Layout.vue'; import Modal from '../components/Modal.vue'; import { api, permission } from '../lib';
const props=defineProps<{years:any[];classrooms:any[];users:any[];rubrics:any[];permissions:string[];registrations:any[]}>();
const tab=ref('academic'),modal=ref(''),entity=ref(''),form=useForm<Record<string,any>>({}),periodText=ref('1.ª Evaluación\n2.ª Evaluación\n3.ª Evaluación');
const teachers=computed(()=>props.users.filter(u=>['teacher','admin'].includes(u.role)));const modules=computed(()=>props.classrooms.flatMap(c=>c.modules.map((m:any)=>({...m,classroom:c.name}))));
const isAdmin=(usePage().props.auth as any).role==='admin';
const formKeys=ref<string[]>([]);
const names:Record<string,string>={year:'Curso académico',classroom:'Clase',student:'Estudiante',teacher:'Profesor',module:'Módulo',rubric:'Rúbrica'};
const labels:Record<string,string>={manage_academics:'Gestionar estructura académica',manage_students:'Gestionar estudiantes',manage_teachers:'Gestionar profesores',manage_modules:'Gestionar módulos',manage_teams:'Gestionar equipos',manage_challenges:'Gestionar retos',manage_rubrics:'Gestionar rúbricas',evaluate_team:'Evaluar el reto y reparto',evaluate_transversal:'Evaluar transversales',enter_exams:'Introducir exámenes',enter_defenses:'Introducir defensas',modify_grades:'Modificar notas existentes',publish_results:'Publicar y reabrir resultados'};
function open(type:string,data?:any,duplicate=false){entity.value=type;form.clearErrors();const initial:Record<string,any>={name:'',...(data?JSON.parse(JSON.stringify(data)):{})};if(duplicate){delete initial.id;initial.name+=' (copia)'} if(type==='year')periodText.value=data?.periods.map((p:any)=>p.name).join('\n')??'1.ª Evaluación\n2.ª Evaluación\n3.ª Evaluación';if(type==='classroom'){initial.academic_year_id=data?.academic_year_id??props.years[0]?.id??'';initial.user_ids=data?.users.map((u:any)=>u.id)??[]}if(['student','teacher'].includes(type)){initial.email=data?.email??'';initial.password='';initial.active=data?.active??true;if(type==='teacher'&&isAdmin)initial.permissions=data?.permissions??[];else delete initial.permissions}if(type==='student')initial.classroom_id=data?.classroom_id??'';if(type==='module'){initial.code=data?.code??'';initial.classroom_id=data?.classroom_id??props.classrooms[0]?.id??'';initial.teacher_ids=data?.teachers.map((u:any)=>u.id)??[]}if(type==='rubric'){initial.kind=data?.kind??'team';initial.items=data?.items??[newItem()]}formKeys.value.forEach(k=>delete (form as any)[k]);Object.assign(form,initial);formKeys.value=Object.keys(initial);modal.value='edit'}
function newItem(){return {key:`c_${Math.random().toString(36).slice(2,10)}`,name:'',description:'',module_id:null,weight:'1',levels:[{score:'4',description:'Necesita acompañamiento'},{score:'6',description:'En desarrollo'},{score:'8',description:'Desempeño autónomo'},{score:'10',description:'Dominio excelente'}]}}
function submit(){form.transform(()=>{const data=Object.fromEntries(formKeys.value.map(k=>[k,form[k]]));if(entity.value==='year')data.periods=periodText.value.split('\n').map(p=>p.trim()).filter(Boolean);return data});form.post(`/setup/${entity.value}`,{onSuccess:()=>{modal.value='';router.reload()}})}
function move(index:number,by:number){const target=index+by;if(target<0||target>=form.items.length)return;[form.items[index],form.items[target]]=[form.items[target],form.items[index]]}
const importKind=ref('student'),importClass=ref(''),file=ref<File|null>(null),importResult=ref<any>(null),importError=ref(''),importBusy=ref(false);
async function importFile(commit=false){if(!file.value)return;importBusy.value=true;importError.value='';try{const data=new FormData();data.append('kind',importKind.value);data.append('commit',commit?'1':'0');data.append('file',file.value);if(importClass.value)data.append('classroom_id',importClass.value);importResult.value=await api('/imports',data);if(importResult.value.committed)router.reload()}catch(e){importError.value=(e as Error).message}finally{importBusy.value=false}}
</script>
<template><Layout><Head title="Organización"/><div class="topline"><span>Organización del centro</span><span>BASES PARA UN BUEN RETO</span></div><header class="page-heading"><div><p class="eyebrow">TODO EN SU SITIO</p><h1>Prepara el aprendizaje<span class="accent">.</span></h1><p class="muted">Cursos, personas y rúbricas. Una base común para todos los retos.</p></div><button v-if="permission('manage_students')||permission('manage_teachers')||permission('manage_modules')" class="button" @click="modal='import';importResult=null"><Upload :size="17"/>Importar CSV / Excel</button></header><div class="tabs section-line"><button :class="{selected:tab==='academic'}" @click="tab='academic'">Cursos y clases</button><button :class="{selected:tab==='teacher'}" @click="tab='teacher'">Profesor</button><button :class="{selected:tab==='student'}" @click="tab='student'">Estudiante</button><button :class="{selected:tab==='modules'}" @click="tab='modules'">Módulos</button><button :class="{selected:tab==='rubrics'}" @click="tab='rubrics'">Biblioteca de rúbricas</button><button v-if="isAdmin" :class="{selected:tab==='registrations'}" @click="tab='registrations'">Solicitudes ({{registrations.length}})</button></div>
<RegistrationRequests v-if="isAdmin&&tab==='registrations'" :registrations="registrations" :classrooms="classrooms"/>
<template v-if="tab==='academic'"><div class="workspace-heading"><h2>Cursos académicos</h2><button v-if="permission('manage_academics')" class="button primary" @click="open('year')"><Plus :size="17"/>Curso</button></div><div class="setup-grid"><section v-for="y in years" class="panel"><div class="actions"><h3>{{y.name}}</h3><button v-if="permission('manage_academics')" class="icon-button" aria-label="Editar curso" @click="open('year',y)"><Pencil :size="16"/></button></div><div class="module-chips"><span v-for="p in y.periods">{{p.name}}</span></div><p class="helper">La nota del curso será la media de estas {{y.periods.length}} Evaluaciones.</p></section></div><div class="workspace-heading"><h2>Clases y matrículas</h2><button v-if="permission('manage_academics')" class="button" @click="open('classroom')"><Plus :size="17"/>Clase</button></div><div class="setup-grid"><section v-for="c in classrooms" class="panel"><div class="actions"><h3>{{c.name}}</h3><span class="muted">{{years.find(y=>y.id===c.academic_year_id)?.name}}</span><button v-if="permission('manage_academics')" class="icon-button" aria-label="Editar clase" @click="open('classroom',c)"><Pencil :size="16"/></button></div><p>{{c.students.length}} estudiantes · {{c.modules.length}} módulos</p><div class="module-chips"><span v-for="m in c.modules">{{m.code}}</span></div></section></div></template>
<template v-if="tab==='teacher'||tab==='student'"><div class="workspace-heading"><h2>{{tab==='student'?'Estudiantes':'Profesores'}}</h2><button v-if="permission(tab==='student'?'manage_students':'manage_teachers')" class="button primary" @click="open(tab)"><Plus :size="17"/>{{tab==='student'?'Estudiante':'Profesor'}}</button></div><p v-if="tab==='student'&&!classrooms.length" class="notice">Crea una clase en Cursos y clases antes de dar de alta estudiantes.</p><div class="table-scroll"><table><thead><tr><th>NOMBRE</th><th>CORREO</th><th v-if="tab==='student'">CLASE</th><th>ESTADO</th><th></th></tr></thead><tbody><tr v-for="u in users.filter(u=>u.role===tab)" :key="u.id"><td>{{u.name}}</td><td>{{u.email}}</td><td v-if="tab==='student'">{{u.classroom?.name??'Pendiente de asignar'}}<small v-if="u.classroom" class="muted"> · {{years.find(y=>y.id===u.classroom.academic_year_id)?.name}}</small></td><td>{{u.active?'Activo':'Desactivado'}}</td><td><button v-if="permission(u.role==='teacher'?'manage_teachers':'manage_students')" class="icon-button" :aria-label="`Editar ${u.name}`" @click="open(u.role,u)"><Pencil :size="17"/></button></td></tr></tbody></table></div></template>
<template v-if="tab==='modules'"><div class="workspace-heading"><h2>Módulos y responsables</h2><button v-if="permission('manage_modules')" class="button primary" @click="open('module')"><Plus :size="17"/>Módulo</button></div><div class="setup-grid"><section v-for="m in modules" class="panel"><div class="actions"><span class="module-chip">{{m.code}}</span><span class="muted">{{m.classroom}}</span><button v-if="permission('manage_modules')" class="icon-button" aria-label="Editar módulo" @click="open('module',m)"><Pencil :size="17"/></button></div><h3>{{m.name}}</h3><p>{{m.teachers.map((t:any)=>t.name).join(', ')}}</p><small class="muted">Sus profesores comparten una sola calificación.</small></section></div></template>
<template v-if="tab==='rubrics'"><div class="workspace-heading"><div><h2>Biblioteca de rúbricas</h2><p>Reutiliza tus criterios. Cada reto conserva su propia versión.</p></div><button v-if="permission('manage_rubrics')" class="button primary" @click="open('rubric')"><Plus :size="17"/>Rúbrica</button></div><div class="setup-grid"><section v-for="r in rubrics" class="panel"><span class="eyebrow">{{r.kind==='team'?'VALORACIÓN DEL RETO':'COMPETENCIAS TRANSVERSALES'}}</span><h3>{{r.name}}</h3><p>{{r.items.map((i:any)=>i.name).join(' · ')}}</p><footer class="actions"><span class="muted">{{r.items.length}} criterios</span><button v-if="permission('manage_rubrics')" class="button" @click="open('rubric',r)"><Pencil :size="15"/>Editar</button><button v-if="permission('manage_rubrics')" class="icon-button" aria-label="Duplicar rúbrica" @click="open('rubric',r,true)"><Copy :size="17"/></button></footer></section></div></template>
<Modal v-if="modal==='edit'" :title="`${form.id?'Editar':'Crear'} ${names[entity]}`" :wide="entity==='rubric'||entity==='teacher'" @close="modal=''"><form @submit.prevent="submit" class="form-grid"><label class="span-2">Nombre<input v-model="form.name" required/></label>
<label v-if="entity==='year'" class="span-2">Evaluaciones, una por línea<textarea v-model="periodText" rows="4" :readonly="!!form.periods_locked" required/><small v-if="form.periods_locked" class="helper">Las Evaluaciones se conservan porque tienen retos. Puedes cambiar el nombre del curso.</small></label>
<template v-if="entity==='classroom'"><label class="span-2">Curso<select v-model="form.academic_year_id" required><option v-for="y in years" :value="y.id">{{y.name}}</option></select></label><fieldset class="span-2 scroll-list"><legend>Profesores de la clase</legend><label v-for="u in users.filter(u=>u.role==='teacher')" class="check"><input v-model="form.user_ids" :value="u.id" type="checkbox"/>{{u.name}} · {{u.role==='teacher'?'Profesor':'Estudiante'}}</label></fieldset><p class="helper span-2">Asigna o cambia la clase de cada estudiante desde la pestaña Estudiante. Los participantes de retos anteriores se conservan.</p></template>
<template v-if="['student','teacher'].includes(entity)"><label class="span-2">Correo<input v-model="form.email" type="email" required/></label><label class="span-2">{{form.id?'Nueva contraseña (opcional)':'Contraseña inicial (mínimo 10 caracteres)'}}<input v-model="form.password" type="password" autocomplete="new-password" :required="!form.id" minlength="10"/></label><label v-if="entity==='student'" class="span-2">Clase<select v-model="form.classroom_id" required><option value="" disabled>Selecciona una clase</option><option v-for="c in classrooms" :value="c.id">{{c.name}} · {{years.find(y=>y.id===c.academic_year_id)?.name}}</option></select><small class="helper">Una clase actual por estudiante. Cambiarla conserva sus retos y notas anteriores.</small><small v-if="!classrooms.length" class="notice">Primero crea una clase en Cursos y clases.</small></label><label class="check span-2"><input v-model="form.active" type="checkbox"/>Cuenta activa</label><fieldset v-if="entity==='teacher'&&isAdmin" class="span-2"><legend>Permisos de escritura · Todas las notas son visibles</legend><label v-for="p in permissions" class="check"><input v-model="form.permissions" type="checkbox" :value="p"/>{{labels[p]}}</label></fieldset></template>
<template v-if="entity==='module'"><label>Código<input v-model="form.code" maxlength="30" required/></label><label>Clase<select v-model="form.classroom_id" required><option v-for="c in classrooms" :value="c.id">{{c.name}}</option></select></label><fieldset class="span-2"><legend>Profesores responsables</legend><label v-for="t in teachers" class="check"><input v-model="form.teacher_ids" :value="t.id" type="checkbox"/>{{t.name}}</label></fieldset></template>
<template v-if="entity==='rubric'"><label class="span-2">Tipo<select v-model="form.kind"><option value="team">Valoración del reto</option><option value="transversal">Competencias transversales</option></select></label><section v-for="(item,index) in form.items" class="rubric-editor span-2"><div class="actions"><strong>Criterio {{Number(index)+1}}</strong><button type="button" class="icon-button" aria-label="Subir criterio" @click="move(Number(index),-1)"><ArrowUp :size="16"/></button><button type="button" class="icon-button" aria-label="Bajar criterio" @click="move(Number(index),1)"><ArrowDown :size="16"/></button><button type="button" class="icon-button" aria-label="Eliminar criterio" @click="form.items.splice(index,1)"><X :size="16"/></button></div><div class="form-grid"><label>Nombre<input v-model="item.name" required/></label><label>Peso<input v-model="item.weight" inputmode="decimal" required/></label><label class="span-2">Descripción<textarea v-model="item.description" rows="2"/></label><label v-if="form.kind==='team'" class="span-2">Módulo<select v-model="item.module_id"><option :value="null">GENERAL</option><option v-for="m in modules" :value="m.id">{{m.code}} · {{m.classroom}}</option></select></label></div><div v-for="(level,li) in item.levels" class="level-editor"><label>Nota<input v-model="level.score" inputmode="decimal" required/></label><label>Descripción del nivel<input v-model="level.description" required/></label><button type="button" class="icon-button" aria-label="Quitar nivel" @click="item.levels.splice(li,1)"><X :size="16"/></button></div><button type="button" class="button small" @click="item.levels.push({score:'10',description:''})">Añadir nivel</button></section><button type="button" class="button span-2" @click="form.items.push(newItem())">Añadir criterio</button><p class="helper span-2">Editar esta plantilla no modifica las rúbricas que ya están asignadas a otros retos.</p></template>
<p v-for="e in form.errors" class="notice error span-2" role="alert">{{e}}</p><button class="button primary span-2" :disabled="form.processing||(entity==='student'&&!classrooms.length)">Guardar</button></form></Modal>
<Modal v-if="modal==='import'" title="Importar datos" @close="modal=''" wide><div class="form-grid"><label>Tipo<select v-model="importKind" @change="importResult=null"><option value="student">Estudiantes</option><option value="teacher">Profesores</option><option value="module">Módulos</option></select></label><label>Clase<select v-model="importClass" @change="importResult=null"><option value="">{{importKind==='teacher'?'Sin asignar':'Selecciona una clase'}}</option><option v-for="c in classrooms" :value="c.id">{{c.name}}</option></select></label><label class="span-2">Archivo CSV o XLSX<input type="file" accept=".csv,.xlsx" @change="file=($event.target as HTMLInputElement).files?.[0]??null;importResult=null"/></label></div><p class="helper">Cabeceras: <code>{{importKind==='module'?'name, code, teacher_email':'name, email'}}</code>. Máximo 1.000 filas y 2 MB. Las nuevas cuentas podrán establecer contraseña mediante el enlace de recuperación cuando el correo esté configurado.</p><button class="button" :disabled="!file||importBusy||(importKind!=='teacher'&&!importClass)" @click="importFile(false)">Validar y previsualizar</button><p v-if="importError" class="notice error">{{importError}}</p><div v-if="importResult"><p v-if="importResult.classroom">Clase: {{importResult.classroom.name}}</p><p>{{importResult.count}} filas válidas · {{importResult.errors.length}} errores</p><p v-for="e in importResult.errors" class="notice error">Fila {{e.row}}: {{e.message}}</p><table><tbody><tr v-for="row in importResult.preview"><td>{{row.name}}</td><td>{{row.email??row.code}}</td></tr></tbody></table><button v-if="!importResult.errors.length&&!importResult.committed" class="button primary full" :disabled="importBusy" @click="importFile(true)">Confirmar importación</button><p v-if="importResult.committed" class="notice success">Importación completada.</p></div></Modal>
</Layout></template>
