<script setup lang="ts">
import { computed, ref, watch } from 'vue'; import { Head, Link, router, useForm, usePage } from '@inertiajs/vue3';
import { Plus, Pencil, Copy, X, Upload } from 'lucide-vue-next';
import GroupCard from '../components/GroupCard.vue';
import RegistrationRequests from '../components/RegistrationRequests.vue';
import Layout from '../components/Layout.vue'; import Modal from '../components/Modal.vue'; import { api, permission } from '../lib';
const props=defineProps<{section:string;title:string;cycleModuleUrl:string;rubricCreateUrl:string;years:any[];classrooms:any[];users:any[];rubrics:any[];permissions:string[];registrations:any[];teachers:any[];cycles:any[];modules:any[]}>();
const tab=computed(()=>({teachers:'teacher',students:'student'} as Record<string,string>)[props.section]??props.section),modal=ref(''),entity=ref(''),form=useForm<Record<string,any>>({});
watch(()=>props.section,()=>{modal.value='';form.clearErrors()});
const selectedCycleId = ref<number|null>(null), moduleSearch = ref('');
const selectedCycle = computed(() => props.cycles.find(c => c.id === selectedCycleId.value));
const cycleModules = computed(() => props.modules.filter(m => m.cycle_id === selectedCycleId.value).sort(byName));
const cycleModuleForm = useForm({cycle_id:0,module_id:0,level:1,active:true});
const normalize = (value:string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es').trim();
const moduleMatches = computed(() => {
  if (!normalize(moduleSearch.value)) return [];
  return props.modules.filter(m => m.cycle_id === null && normalize(m.name).includes(normalize(moduleSearch.value))).sort(byName);
});
function viewCycleModules(cycle:any) {
  selectedCycleId.value=cycle.id;moduleSearch.value='';cycleModuleForm.reset();cycleModuleForm.clearErrors();modal.value='cycle-modules';
}
function setCycleModule(module:any,active:boolean) {
  cycleModuleForm.cycle_id=selectedCycleId.value!;cycleModuleForm.module_id=module.id;cycleModuleForm.active=active;
  cycleModuleForm.clearErrors();
  cycleModuleForm.post(props.cycleModuleUrl,{preserveScroll:true});
}
const moduleCycle = ref(''), moduleLevel = ref(''), moduleDescending = ref(false), cycleDescending = ref(false);
const byName = (a:any,b:any) => a.name.localeCompare(b.name,'es',{sensitivity:'base',numeric:true});
const sortedCycles = computed(() => [...props.cycles].sort((a,b) => byName(a,b)*(cycleDescending.value?-1:1)));
const filteredModules = computed(() => props.modules.filter(m => (!moduleCycle.value||(moduleCycle.value==='unassigned'?m.cycle_id===null:m.cycle_id===Number(moduleCycle.value)))&&(!moduleLevel.value||m.level===Number(moduleLevel.value))).sort((a,b) => byName(a,b)*(moduleDescending.value?-1:1)));
const teachers=computed(()=>props.teachers);const modules=computed(()=>props.modules);
const year=computed(()=>(usePage().props.academic as any)?.year);const canWork=computed(()=>!!year.value?.is_open);
const responsibilityClass=computed(()=>props.classrooms.find(c=>c.id===Number(form.classroom_id)));
const isAdmin=(usePage().props.auth as any).role==='admin';
const formKeys=ref<string[]>([]);
const names:Record<string,string>={year:'Curso académico',cycle:'Ciclo',enrollment:'Matrícula',responsibility:'Responsables de módulo',classroom:'Grupo','group-periods':'Evaluaciones del grupo',student:'Estudiante',teacher:'Profesor',module:'Módulo'};
function open(type:string,data?:any){entity.value=type;form.clearErrors();const initial:Record<string,any>={name:'',...(data?JSON.parse(JSON.stringify(data)):{})};
if(type==='group-periods'){initial.classroom_id=data.id;initial.periods=data.periods.map((p:any)=>({id:p.id,name:p.name,challenges_count:p.challenges_count}));delete initial.id}
if(['classroom','module'].includes(type)){initial.cycle_id=data?(data.cycle_id??''):(props.cycles[0]?.id??'');initial.level=data?.level??2}
if(type==='classroom'){initial.period_count=data?.periods?.length??3;initial.user_ids=data?.users?.map((u:any)=>u.id)??[];initial.owner_id=data?.owner_id??(usePage().props.auth as any).id}
if(['student','teacher'].includes(type)){initial.email=data?.email??'';initial.password='';initial.active=data?.active??true;delete initial.permissions}
if(type==='student')initial.classroom_id='';
if(['module','cycle'].includes(type))initial.code=data?.code??'';
if(type==='enrollment'){initial.classroom_id=data?.classroom_id??props.classrooms[0]?.id??'';initial.email=data?.email??'';initial.active=true}
formKeys.value.forEach(k=>delete (form as any)[k]);Object.assign(form,initial);formKeys.value=Object.keys(initial);modal.value='edit'}
function copyRubric(id:number){router.post('/setup/rubric-copy',{id})}
function yearStatus(y:any){router.post('/setup/year-status',{id:y.id,is_open:!y.is_open})}
function endEnrollment(u:any,e:any){router.post('/setup/enrollment',{email:u.email,classroom_id:e.classroom_id,active:false})}
const foundStudent=ref<any>(null),lookupError=ref('');
async function lookup(){foundStudent.value=null;lookupError.value='';try{foundStudent.value=(await api('/students/lookup',{email:form.email,classroom_id:form.classroom_id})).student;if(!foundStudent.value)lookupError.value='No se ha encontrado un estudiante activo con ese correo.'}catch(e){lookupError.value=(e as Error).message}}
function submit(){form.transform(()=>{const data=Object.fromEntries(formKeys.value.map(k=>[k,form[k]]));return data});form.post(`/setup/${entity.value}`,{onSuccess:()=>{modal.value='';router.reload()}})}
const importCycle=ref(''),importLevel=ref(2);
const importFormats:Record<string,{item:string;columns:string[];example:string[]}>={student:{item:'estudiante',columns:['nombre','email'],example:['Ane Etxeberria','ane.etxeberria@ejemplo.com']},teacher:{item:'profesor',columns:['name','email'],example:['Iker Garmendia','iker.garmendia@ejemplo.com']},module:{item:'módulo',columns:['name','code'],example:['Programación','PROG']}};
const importKind=ref('student'),importClass=ref(''),file=ref<File|null>(null),importResult=ref<any>(null),importError=ref(''),importBusy=ref(false);
async function importFile(commit=false){if(!file.value)return;importBusy.value=true;importError.value='';try{const data=new FormData();data.append('kind',importKind.value);data.append('commit',commit?'1':'0');data.append('file',file.value);if(importKind.value==='student'&&importClass.value)data.append('classroom_id',importClass.value);if(importKind.value==='module'){data.append('cycle_id',importCycle.value);data.append('level',String(importLevel.value))}importResult.value=await api('/imports',data);if(importResult.value.committed)router.reload()}catch(e){importError.value=(e as Error).message}finally{importBusy.value=false}}
</script>
<template><Layout><Head :title="title"/><div class="topline"><span>Organización / {{title}}</span><span>BASES PARA UN BUEN RETO</span></div><header class="page-heading"><div><h1>{{title}}<span class="accent">.</span></h1><p class="muted">Gestiona esta sección y accede al resto desde el menú Organización.</p></div><button v-if="(isAdmin&&['teacher','modules'].includes(tab))||(tab==='student'&&canWork&&classrooms.length)" class="button" @click="importKind=tab==='modules'?'module':tab;modal='import';importResult=null"><Upload :size="17"/>Importar CSV / Excel</button></header>
<RegistrationRequests v-if="isAdmin&&tab==='registrations'" :registrations="registrations" :classrooms="classrooms"/>
<template v-if="tab==='courses'"><div class="workspace-heading"><h2>Cursos académicos</h2><button v-if="permission('manage_academics')" class="button primary" @click="open('year')"><Plus :size="17"/>Curso</button></div><div class="setup-grid"><section v-for="y in years" class="panel"><div class="actions"><h3>{{y.name}}</h3><span class="badge">{{y.is_open?'Abierto':'Cerrado'}}</span><button class="button small" @click="yearStatus(y)">{{y.is_open?'Cerrar curso':'Reabrir curso'}}</button><button v-if="isAdmin&&y.is_open" class="icon-button" aria-label="Editar curso" @click="open('year',y)"><Pencil :size="16"/></button></div><p class="helper">Cada grupo configura sus propias evaluaciones.</p></section></div></template><template v-if="tab==='classrooms'"><div class="workspace-heading"><h2>Grupos y matrículas</h2><p v-if="!cycles.length" class="helper">Administración debe configurar primero los ciclos y módulos.</p><button v-if="canWork&&cycles.length" class="button" @click="open('classroom')"><Plus :size="17"/>Grupo</button></div><div class="setup-grid"><GroupCard v-for="c in classrooms" :key="c.id" :group="c" :catalog="modules" :writable="canWork" @edit="open('classroom',$event)" @periods="open('group-periods',$event)" @responsibility="open('responsibility',$event)"/></div></template>
<template v-if="tab==='cycles'"><div class="workspace-heading"><h2>Ciclos de Formación Profesional</h2><button class="button primary" @click="open('cycle')"><Plus :size="17"/>Ciclo</button></div>
<div class="table-scroll"><table aria-label="Ciclos"><thead><tr><th scope="col">CÓDIGO</th><th scope="col" :aria-sort="cycleDescending?'descending':'ascending'"><button @click="cycleDescending=!cycleDescending">Nombre {{cycleDescending?'↓':'↑'}}</button></th><th scope="col">ACCIONES</th></tr></thead><tbody><tr v-for="c in sortedCycles" :key="c.id"><td>{{c.code}}</td><td>{{c.name}}</td><td><div class="actions"><button class="button small" @click="open('cycle',c)">Editar ciclo</button><button class="button small" @click="viewCycleModules(c)">Ver módulos</button></div></td></tr><tr v-if="!sortedCycles.length"><td colspan="3">Todavía no hay ciclos.</td></tr></tbody></table></div></template>
<template v-if="tab==='teacher'||tab==='student'"><div class="workspace-heading"><h2>{{tab==='student'?'Estudiantes':'Profesores'}}</h2><button v-if="tab==='student'&&canWork&&classrooms.length" class="button" @click="foundStudent=null;lookupError='';open('enrollment')">Matricular por correo</button><button v-if="isAdmin||(canWork&&classrooms.length)" class="button primary" @click="open(tab)"><Plus :size="17"/>{{tab==='student'?'Estudiante':'Profesor'}}</button></div><p v-if="tab==='student'&&!classrooms.length" class="notice">Crea un grupo en Organización → Grupos antes de dar de alta estudiantes.</p><div class="table-scroll"><table><thead><tr><th>NOMBRE</th><th>CORREO</th><th v-if="tab==='student'">GRUPO</th><th>ESTADO</th><th></th></tr></thead><tbody><tr v-for="u in users.filter(u=>u.role===tab)" :key="u.id"><td>{{u.name}}</td><td>{{u.email}}</td><td v-if="tab==='student'"><div v-for="e in u.enrollments">{{classrooms.find(c=>c.id===e.classroom_id)?.name}} <small v-if="e.ended_at">(histórico)</small><button v-else-if="canWork" class="button small" @click="endEnrollment(u,e)">Dar de baja</button></div><span v-if="!u.enrollments.length">Sin matrícula en este curso</span></td><td>{{u.active?'Activo':'Desactivado'}}</td><td><button v-if="isAdmin" class="icon-button" :aria-label="`Editar ${u.name}`" @click="open(u.role,u)"><Pencil :size="17"/></button></td></tr></tbody></table></div></template>
<template v-if="tab==='modules'"><div class="workspace-heading"><h2>Catálogo de módulos</h2><button v-if="permission('manage_modules')" class="button primary" @click="open('module')"><Plus :size="17"/>Módulo</button></div>
<div class="catalog-filters"><label>Ciclo<select v-model="moduleCycle"><option value="">Todos los ciclos</option><option value="unassigned">Sin ciclo asignado</option><option v-for="c in cycles" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Curso<select v-model="moduleLevel"><option value="">Todos los cursos</option><option v-for="n in 4" :key="n" :value="n">{{n}}.º</option></select></label></div>
<div class="table-scroll"><table aria-label="Módulos"><thead><tr><th scope="col">CÓDIGO</th><th scope="col" :aria-sort="moduleDescending?'descending':'ascending'"><button @click="moduleDescending=!moduleDescending">Nombre {{moduleDescending?'↓':'↑'}}</button></th><th scope="col">CICLO</th><th scope="col">CURSO</th><th scope="col">ACCIONES</th></tr></thead><tbody><tr v-for="m in filteredModules" :key="m.id"><td>{{m.code}}</td><td>{{m.name}}</td><td>{{m.cycle?.name??'Sin ciclo asignado'}}</td><td>{{m.level}}.º</td><td><button v-if="permission('manage_modules')" class="button small" @click="open('module',m)">Editar módulo</button></td></tr><tr v-if="!filteredModules.length"><td colspan="5">No hay módulos que coincidan con los filtros.</td></tr></tbody></table></div></template>
<template v-if="tab==='rubrics'"><div class="workspace-heading"><div><h2>Biblioteca de rúbricas</h2><p>Reutiliza tus criterios. Cada reto conserva su propia versión.</p></div><Link v-if="permission('manage_rubrics')" class="button primary" :href="rubricCreateUrl"><Plus :size="17"/>Rúbrica</Link></div><div class="setup-grid"><section v-for="r in rubrics" class="panel"><span class="eyebrow">{{r.kind==='team'?'VALORACIÓN DEL RETO':'COMPETENCIAS TRANSVERSALES'}}</span><h3>{{r.name}}</h3><small class="muted">{{r.owner_id===(usePage().props.auth as any).id?'Propia':'Compartida para usar y copiar'}}</small><p>{{r.items.map((i:any)=>i.name).join(' · ')}}</p><footer class="actions"><span class="muted">{{r.items.length}} criterios</span><Link v-if="isAdmin||r.owner_id===(usePage().props.auth as any).id" class="button" :href="r.edit_url"><Pencil :size="15"/>Editar</Link><button v-if="permission('manage_rubrics')" class="icon-button" aria-label="Duplicar rúbrica" @click="copyRubric(r.id)"><Copy :size="17"/></button></footer></section></div></template>
<Modal v-if="modal==='cycle-modules'&&selectedCycle" :title="`Módulos de ${selectedCycle.name}`" wide @close="modal=''">
<p class="helper">Al quitar un módulo queda sin ciclo asignado. Los grupos y notas existentes se conservan.</p>
<div class="table-scroll"><table aria-label="Módulos del ciclo"><thead><tr><th scope="col">NOMBRE</th><th scope="col">CÓDIGO</th><th scope="col">CURSO</th><th scope="col">ACCIONES</th></tr></thead><tbody><tr v-for="m in cycleModules" :key="m.id"><td>{{m.name}}</td><td>{{m.code}}</td><td>{{m.level}}.º</td><td><button class="button small" :disabled="cycleModuleForm.processing" :aria-label="`Quitar ${m.name}`" @click="setCycleModule(m,false)">Quitar</button></td></tr><tr v-if="!cycleModules.length"><td colspan="4">Este ciclo todavía no incluye módulos.</td></tr></tbody></table></div>
<h3 class="catalog-subheading">Añadir módulos</h3>
<div class="catalog-filters"><label>Buscar módulos por nombre<input v-model="moduleSearch" type="search" placeholder="Escribe el nombre de un módulo"/></label><label>Curso de destino<select v-model="cycleModuleForm.level"><option v-for="n in 4" :key="n" :value="n">{{n}}.º</option></select></label></div>
<p class="helper">Solo se muestran módulos sin ciclo asignado. Se añadirán al curso seleccionado.</p>
<p v-for="error in cycleModuleForm.errors" :key="error" class="notice error" role="alert">{{error}}</p>
<div class="scroll-list"><div v-for="m in moduleMatches" :key="m.id" class="breakdown-row"><span>{{m.name}} <small class="muted">{{m.code}}</small></span><button class="button small" :disabled="cycleModuleForm.processing" :aria-label="`Añadir ${m.name}`" @click="setCycleModule(m,true)">Añadir</button></div></div>
<p v-if="moduleSearch.trim()&&!moduleMatches.length" class="helper">No hay módulos disponibles que coincidan con la búsqueda para ese curso.</p>
</Modal>
<Modal v-if="modal==='edit'" :title="entity==='group-periods'?'Evaluaciones del grupo':`${form.id?'Editar':'Crear'} ${names[entity]}`" :wide="entity==='teacher'" @close="modal=''"><form @submit.prevent="submit" class="form-grid"><label v-if="!['enrollment','responsibility','group-periods'].includes(entity)" class="span-2">Nombre<input v-model="form.name" required/></label>
<template v-if="entity==='group-periods'">
<p class="helper span-2">{{form.name}} · {{form.periods.length}} evaluaciones. Las que tienen retos conservan su nombre y no se pueden eliminar.</p>
<div v-for="(period,index) in form.periods" :key="period.id??`new-${index}`" class="level-editor period-editor span-2"><label>Evaluación {{Number(index)+1}}<input v-model="period.name" :readonly="!!period.challenges_count" required maxlength="100"/></label><button type="button" class="icon-button" :aria-label="`Quitar evaluación ${Number(index)+1}`" :disabled="!!period.challenges_count||form.periods.length===1" @click="form.periods.splice(Number(index),1)"><X :size="16"/></button></div>
<button type="button" class="button span-2" :disabled="form.periods.length>=12" @click="form.periods.push({name:'',challenges_count:0})">Añadir evaluación</button>
</template>
<template v-if="['classroom','module'].includes(entity)"><label>Ciclo<select v-model="form.cycle_id" :required="entity==='classroom'" :disabled="!!form.id"><option value="">{{entity==='module'?'Sin ciclo asignado':'Selecciona'}}</option><option v-for="c in cycles" :value="c.id">{{c.name}}</option></select></label><label>Curso / nivel<select v-model="form.level" required :disabled="!!form.id"><option v-for="n in 4" :value="n">{{n}}.º</option></select></label></template>
<template v-if="entity==='classroom'"><label v-if="!form.id" class="span-2">Número de evaluaciones<input v-model="form.period_count" type="number" min="1" max="12" required/></label><p class="helper span-2">Curso académico: {{year?.name}}. Al crearlo se añaden los módulos de su ciclo y nivel. Después puedes añadirlos o quitarlos desde Grupos.</p><label v-if="isAdmin" class="span-2">Propietario<select v-model="form.owner_id"><option v-for="t in teachers" :value="t.id">{{t.name}}</option></select></label><fieldset class="span-2 scroll-list"><legend>Profesores del grupo</legend><label v-for="t in teachers" class="check"><input v-model="form.user_ids" :value="t.id" type="checkbox"/>{{t.name}}</label></fieldset></template>
<template v-if="entity==='responsibility'"><p class="span-2">{{responsibilityClass?.name}} · {{responsibilityClass?.modules.find((m:any)=>m.id===form.module_id)?.name}}</p><fieldset class="span-2"><legend>Profesores responsables</legend><label v-for="t in responsibilityClass?.users" class="check"><input v-model="form.teacher_ids" :value="t.id" type="checkbox"/>{{t.name}}</label></fieldset></template>
<template v-if="entity==='enrollment'"><label class="span-2">Grupo<select v-model="form.classroom_id" required><option v-for="c in classrooms" :value="c.id">{{c.name}}</option></select></label><label class="span-2">Correo exacto del estudiante<input v-model="form.email" type="email" required @input="foundStudent=null"/></label><button type="button" class="button span-2" @click="lookup">Buscar estudiante</button><p v-if="foundStudent" class="notice success span-2">{{foundStudent.name}} · {{foundStudent.email}}</p><p v-if="lookupError" class="notice span-2">{{lookupError}}</p><p class="helper span-2">Se añade esta matrícula conservando los demás grupos y su histórico.</p></template>
<template v-if="entity==='cycle'"><label class="span-2">Código<input v-model="form.code" required maxlength="30"/></label></template>
<template v-if="['student','teacher'].includes(entity)"><label class="span-2">Correo<input v-model="form.email" type="email" required/></label><label class="span-2">{{form.id?'Nueva contraseña (opcional)':'Contraseña inicial (mínimo 10 caracteres)'}}<input v-model="form.password" type="password" autocomplete="new-password" :required="!form.id" minlength="10"/></label><label v-if="entity==='student'&&canWork" class="span-2">Añadir matrícula en un grupo<select v-model="form.classroom_id" :required="!isAdmin"><option value="">{{isAdmin?'Sin añadir matrícula':'Selecciona un grupo'}}</option><option v-for="c in classrooms" :value="c.id">{{c.name}}</option></select><small class="helper">La cuenta se conserva entre años. Puede tener varias matrículas.</small></label><label v-if="isAdmin" class="check span-2"><input v-model="form.active" type="checkbox"/>Cuenta activa</label></template>
<template v-if="entity==='module'"><label class="span-2">Código<input v-model="form.code" maxlength="30" required/></label></template>
<p v-for="e in form.errors" class="notice error span-2" role="alert">{{e}}</p><button class="button primary span-2" :disabled="form.processing||(entity==='student'&&!isAdmin&&(!canWork||!classrooms.length))">Guardar</button></form></Modal>
<Modal v-if="modal==='import'" title="Importar datos" @close="modal=''" wide><div class="form-grid"><label>Tipo<select v-model="importKind" @change="importResult=null"><option value="student">Estudiantes</option><option v-if="isAdmin" value="teacher">Profesores</option><option v-if="isAdmin" value="module">Módulos</option></select></label><label v-if="importKind==='student'">Grupo<select v-model="importClass" @change="importResult=null"><option value="">Selecciona un grupo</option><option v-for="c in classrooms" :value="c.id">{{c.name}}</option></select></label><template v-if="importKind==='module'"><label>Ciclo<select v-model="importCycle" @change="importResult=null"><option value="">Selecciona</option><option v-for="c in cycles" :value="c.id">{{c.name}}</option></select></label><label>Curso / nivel<select v-model="importLevel" @change="importResult=null"><option v-for="n in 4" :value="n">{{n}}.º</option></select></label></template><label class="span-2">Archivo CSV o XLSX<input type="file" accept=".csv,.xlsx" @change="file=($event.target as HTMLInputElement).files?.[0]??null;importResult=null"/></label></div><div class="notice info import-format"><p><strong>Estructura del archivo.</strong> La primera fila debe contener estas cabeceras: <code v-for="(column,index) in importFormats[importKind].columns" :key="column">{{index?', ':''}}{{column}}</code> (en mayúsculas o minúsculas). Debajo, una fila por {{importFormats[importKind].item}}. Ejemplo:</p><table><thead><tr><th v-for="column in importFormats[importKind].columns" :key="column">{{column}}</th></tr></thead><tbody><tr><td v-for="value in importFormats[importKind].example" :key="value">{{value}}</td></tr></tbody></table></div><p class="helper">Máximo 1.000 filas y 2 MB. Las nuevas cuentas podrán establecer contraseña mediante el enlace de recuperación cuando el correo esté configurado.</p><button class="button" :disabled="!file||importBusy||(importKind==='student'&&!importClass)||(importKind==='module'&&!importCycle)" @click="importFile(false)">Validar y previsualizar</button><p v-if="importError" class="notice error">{{importError}}</p><div v-if="importResult"><p v-if="importResult.classroom">Grupo: {{importResult.classroom.name}}</p><p>{{importResult.count}} filas válidas · {{importResult.errors.length}} errores</p><p v-for="e in importResult.errors" class="notice error">Fila {{e.row}}: {{e.message}}</p><table><tbody><tr v-for="row in importResult.preview"><td>{{row.name}}</td><td>{{row.email??row.code}}</td></tr></tbody></table><button v-if="!importResult.errors.length&&!importResult.committed" class="button primary full" :disabled="importBusy" @click="importFile(true)">Confirmar importación</button><p v-if="importResult.committed" class="notice success">Importación completada.</p></div></Modal>
</Layout></template>

<style scoped>
.catalog-subheading { margin: 24px 0 12px; }
.catalog-filters { display: flex; flex-wrap: wrap; gap: 16px; margin-bottom: 18px; }
.catalog-filters label { flex: 1 1 180px; min-width: 0; }
.catalog-filters select { width: 100%; }
.period-editor > label:first-child { flex: 1; width: auto; min-width: 0; }
</style>
