<script setup lang="ts">
import { ref } from 'vue'; import { Head, Link, usePage } from '@inertiajs/vue3';
import { ArrowLeft, Check, HeartHandshake } from 'lucide-vue-next';
import Layout from '../components/Layout.vue'; import { api, grade, statusLabel } from '../lib';
const props=defineProps<{book:any}>(); const book=ref(props.book),busy=ref(false),error=ref(''),message=ref('');const auth=usePage().props.auth as any;
const selected=ref(auth.id);const kind=()=>selected.value===auth.id?'self':'peer';
const value=(key:string)=>book.value.assessments.find((a:any)=>a.kind===kind()&&a.subject_id===selected.value&&a.criterion===key)?.level;
async function save(key:string,level:number){busy.value=true;error.value='';try{const data=await api(`/challenges/${book.value.challenge.id}`,{revision:book.value.challenge.revision,action:'assess',kind:kind(),entries:[{subject_id:selected.value,criterion:key,level}]});book.value=data.book;message.value='Evaluación guardada'}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
</script>
<template><Layout><Head :title="book.challenge.name"/><div class="topline"><Link href="/" class="back-link"><ArrowLeft :size="16"/>Mis retos</Link><span>{{book.classroom}} · {{book.period}}</span></div><header class="page-heading"><div><p class="eyebrow">TU APRENDIZAJE, PASO A PASO</p><h1>{{book.challenge.name}}</h1><p class="muted">{{book.challenge.description}}</p></div><span class="badge" :class="book.challenge.status">{{statusLabel[book.challenge.status]}}</span></header><div v-if="book.result" class="student-results"><h2>Tus resultados publicados</h2><div class="overview-grid"><div class="overview-card"><span>Transversales</span><strong>{{grade(book.result.transversal)}}</strong></div><div class="overview-card highlight"><span>Nota final del reto</span><strong>{{grade(book.result.challenge_final)}}</strong></div><div class="overview-card"><span>Reparto / base + defensas</span><strong class="small-value">{{grade(book.result.base)}} + {{grade(book.result.defenses_total)}}</strong></div></div><div class="module-breakdowns"><section v-for="m in book.modules"><h3>{{m.code}}</h3><p>Examen: {{grade(book.result.modules[m.id].exam)}}</p><p v-if="m.defense_enabled">Defensa: {{grade(book.result.modules[m.id].defense)}}</p><strong>{{grade(book.result.modules[m.id].final)}}</strong></section></div></div><section class="panel"><div class="workspace-heading"><div><h2>Reflexiona sobre el trabajo en equipo</h2><p>Valora tu participación y la de tus compañeros con la rúbrica del reto.</p></div><span class="save-status" role="status">{{message}}</span></div><div class="person-tabs"><button :class="{selected:selected===auth.id}" @click="selected=auth.id">Mi autoevaluación</button><button v-for="p in book.peers.filter((p:any)=>p.id!==auth.id)" :class="{selected:selected===p.id}" @click="selected=p.id">{{p.name}}</button></div><p v-if="!['active','evaluating'].includes(book.challenge.status)" class="notice warning">La evaluación del alumnado está cerrada en este estado del reto.</p><p v-if="error" class="notice error" role="alert">{{error}}</p><section v-for="item in book.challenge.transversal_rubric.items" class="student-rubric"><h3>{{item.name}}</h3><p>{{item.description}}</p><div class="student-levels"><button v-for="(level,index) in item.levels" :class="{chosen:value(item.key)===index}" :disabled="busy||!['active','evaluating'].includes(book.challenge.status)" @click="save(item.key,Number(index))"><strong>{{level.score}}</strong><span>{{level.description}}</span><Check v-if="value(item.key)===index" :size="18"/></button></div></section></section></Layout></template>
